import type { Banner, Category, Product } from "@/types";

const IMG = "https://images.unsplash.com";

export const demoCategories: Category[] = [
  {
    _id: "demo-controllers",
    name: "Controllers",
    slug: "controllers",
    description: "Responsive wireless controllers for every platform",
    image: `${IMG}/photo-1606144042614-b2417e99c4e3?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 0,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-headsets",
    name: "Headsets",
    slug: "headsets",
    description: "Immersive audio and clear team comms",
    image: `${IMG}/photo-1583394838336-acd977736f90?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 1,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-keyboards",
    name: "Keyboards",
    slug: "keyboards",
    description: "Mechanical keyboards built for fast input",
    image: `${IMG}/photo-1541140532154-b024d705b90a?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 2,
    createdAt: new Date().toISOString(),
  },
];

export const demoBanners: Banner[] = [
  {
    _id: "demo-banner-1",
    title: "Upgrade Your Battle Station",
    subtitle: "Premium Gaming Gear",
    description:
      "Controllers, headsets, keyboards, and mice selected for smooth wins and clean setups.",
    image: `${IMG}/photo-1593305841991-05c297ba4575?w=1600&h=800&fit=crop&q=80`,
    ctaText: "Shop Gear",
    ctaLink: "/categories",
    secondaryCtaText: "Explore Deals",
    secondaryCtaLink: "/categories?filter=featured",
    isActive: true,
    sortOrder: 0,
    position: "hero",
  },
];

export const demoProducts: Product[] = [
  {
    _id: "demo-pro-controller",
    name: "Apex Wireless Controller",
    slug: "apex-wireless-controller",
    category: demoCategories[0],
    brand: "RetroForge",
    price: 79.99,
    salePrice: 64.99,
    discountPercentage: 19,
    stockQuantity: 48,
    sku: "RG-CTRL-APEX",
    description:
      "Low-latency wireless controller with textured grips, responsive triggers, and all-day battery life.",
    shortDescription: "Low-latency controller with textured grips",
    specifications: [],
    tags: ["controller", "wireless", "gaming"],
    mainImage: `${IMG}/photo-1606144042614-b2417e99c4e3?w=900&h=900&fit=crop&q=80`,
    galleryImages: [],
    imageTransition: "fade",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.8,
    reviewCount: 124,
    views: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-neon-headset",
    name: "Nova RGB Gaming Headset",
    slug: "nova-rgb-gaming-headset",
    category: demoCategories[1],
    brand: "PulseArc",
    price: 129.99,
    salePrice: 99.99,
    discountPercentage: 23,
    stockQuantity: 32,
    sku: "RG-HDS-NOVA",
    description:
      "Surround sound headset with plush ear cups, RGB accents, and a crisp detachable microphone.",
    shortDescription: "Surround headset with RGB and detachable mic",
    specifications: [],
    tags: ["headset", "audio", "rgb"],
    mainImage: `${IMG}/photo-1583394838336-acd977736f90?w=900&h=900&fit=crop&q=80`,
    galleryImages: [],
    imageTransition: "zoom",
    isFeatured: true,
    isTrending: false,
    isNewArrival: true,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.7,
    reviewCount: 91,
    views: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-mech-keyboard",
    name: "Flux Mechanical Keyboard",
    slug: "flux-mechanical-keyboard",
    category: demoCategories[2],
    brand: "KeyVolt",
    price: 149.99,
    salePrice: 119.99,
    discountPercentage: 20,
    stockQuantity: 25,
    sku: "RG-KBD-FLUX",
    description:
      "Compact mechanical keyboard with hot-swappable switches, per-key RGB, and a sturdy aluminum frame.",
    shortDescription: "Hot-swappable compact mechanical keyboard",
    specifications: [],
    tags: ["keyboard", "mechanical", "rgb"],
    mainImage: `${IMG}/photo-1541140532154-b024d705b90a?w=900&h=900&fit=crop&q=80`,
    galleryImages: [],
    imageTransition: "slide",
    isFeatured: true,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    isActive: true,
    isOutOfStock: false,
    rating: 4.9,
    reviewCount: 78,
    views: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
