import type { Category, Product } from "@/types";

const IMG = "https://images.unsplash.com";

// ─── PlayStation Categories ──────────────────────────────────────────────────

export const demoPSCategories: Category[] = [
  {
    _id: "demo-ps5",
    name: "PlayStation 5",
    slug: "playstation-5",
    description: "Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with haptic feedback, adaptive triggers, and 3D Audio",
    image: `${IMG}/photo-1606144042614-b2417e99c4e3?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 0,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps5-slim",
    name: "PlayStation 5 Slim",
    slug: "playstation-5-slim",
    description: "The slimmest PlayStation 5 console ever with a smaller form factor and all the same powerful features",
    image: `${IMG}/photo-1621259182978-fbf93132d53d?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 1,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps5-pro",
    name: "PlayStation 5 Pro",
    slug: "playstation-5-pro",
    description: "The most powerful PlayStation console with enhanced GPU, ray tracing, and AI-driven upscaling",
    image: `${IMG}/photo-1606144042614-b2417e99c4e3?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 2,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps4-pro",
    name: "PlayStation 4 Pro",
    slug: "playstation-4-pro",
    description: "Enhanced PS4 with 4K gaming and HDR support for stunning visuals",
    image: `${IMG}/photo-1606144042614-b2417e99c4e3?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 3,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps4-slim",
    name: "PlayStation 4 Slim",
    slug: "playstation-4-slim",
    description: "Sleek and compact PS4 with all the features you love in a slimmer design",
    image: `${IMG}/photo-1606144042614-b2417e99c4e3?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 4,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps-vr",
    name: "PlayStation VR",
    slug: "playstation-vr",
    description: "Immerse yourself in virtual reality with PlayStation VR headsets and accessories",
    image: `${IMG}/photo-1622979135225-d2ba269cf1ac?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 5,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-psp",
    name: "PlayStation Portable",
    slug: "playstation-portable",
    description: "Take your gaming on the go with PlayStation Portable and handheld devices",
    image: `${IMG}/photo-1592840496694-26d035b52b48?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 6,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps-accessories",
    name: "PlayStation Accessories",
    slug: "playstation-accessories",
    description: "Essential accessories to enhance your PlayStation gaming experience",
    image: `${IMG}/photo-1606144042614-b2417e99c4e3?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 7,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps-controllers",
    name: "PlayStation Controllers",
    slug: "playstation-controllers",
    description: "Official DualSense and DualShock controllers for PlayStation consoles",
    image: `${IMG}/photo-1592840496694-26d035b52b48?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 8,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps-bundles",
    name: "PlayStation Bundles",
    slug: "playstation-bundles",
    description: "Complete PlayStation bundles with consoles, games, and accessories",
    image: `${IMG}/photo-1606144042614-b2417e99c4e3?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 9,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps-refurbished",
    name: "Refurbished PlayStations",
    slug: "refurbished-playstations",
    description: "Certified refurbished PlayStation consoles tested to meet original factory specifications",
    image: `${IMG}/photo-1606144042614-b2417e99c4e3?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 10,
    createdAt: new Date().toISOString(),
  },
];

// ─── Xbox Categories ────────────────────────────────────────────────────────

export const demoXboxCategories: Category[] = [
  {
    _id: "demo-xbox-series-x",
    name: "Xbox Series X",
    slug: "xbox-series-x",
    description: "The fastest, most powerful Xbox ever with 4K gaming at up to 120fps",
    image: `${IMG}/photo-1621259182978-fbf93132d53d?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 0,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-series-s",
    name: "Xbox Series S",
    slug: "xbox-series-s",
    description: "Next-gen performance in the smallest Xbox ever with 1440p gaming",
    image: `${IMG}/photo-1621259182978-fbf93132d53d?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 1,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-one-x",
    name: "Xbox One X",
    slug: "xbox-one-x",
    description: "The world's most powerful console with true 4K gaming",
    image: `${IMG}/photo-1621259182978-fbf93132d53d?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 2,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-one-s",
    name: "Xbox One S",
    slug: "xbox-one-s",
    description: "Sleek design with 4K Ultra HD and HDR gaming",
    image: `${IMG}/photo-1621259182978-fbf93132d53d?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 3,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-one",
    name: "Xbox One",
    slug: "xbox-one",
    description: "The original Xbox One with a vast library of games",
    image: `${IMG}/photo-1621259182978-fbf93132d53d?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 4,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-controllers",
    name: "Xbox Controllers",
    slug: "xbox-controllers",
    description: "Wireless and wired controllers for Xbox consoles and PC",
    image: `${IMG}/photo-1592840496694-26d035b52b48?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 5,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-accessories",
    name: "Xbox Accessories",
    slug: "xbox-accessories",
    description: "Headsets, charging kits, and more for Xbox",
    image: `${IMG}/photo-1621259182978-fbf93132d53d?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 6,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-bundles",
    name: "Xbox Bundles",
    slug: "xbox-bundles",
    description: "Complete Xbox bundles with consoles, games, and subscriptions",
    image: `${IMG}/photo-1621259182978-fbf93132d53d?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 7,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-refurbished",
    name: "Refurbished Xbox Consoles",
    slug: "refurbished-xbox-consoles",
    description: "Certified refurbished Xbox consoles at great prices",
    image: `${IMG}/photo-1621259182978-fbf93132d53d?w=640&h=420&fit=crop&q=80`,
    isActive: true,
    sortOrder: 8,
    createdAt: new Date().toISOString(),
  },
];

// ─── PlayStation Products ────────────────────────────────────────────────────

export const demoPSProducts: Product[] = [
  {
    _id: "demo-ps5-console",
    name: "PlayStation 5 Console (Disc Edition)",
    slug: "playstation-5-console-disc",
    category: demoPSCategories[0],
    brand: "Sony",
    price: 499.99,
    salePrice: 479.99,
    discountPercentage: 4,
    stockQuantity: 35,
    sku: "SONY-PS5-DISC",
    description:
      "Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with haptic feedback, adaptive triggers, and 3D Audio. The PS5 console includes a DualSense wireless controller, HDMI cable, AC power cord, base, and USB cable.",
    shortDescription: "Next-gen PlayStation with disc drive and DualSense controller",
    specifications: [
      { key: "CPU", value: "AMD Zen 2, 8 cores at 3.5GHz" },
      { key: "GPU", value: "AMD RDNA 2, 10.28 TFLOPS" },
      { key: "RAM", value: "16GB GDDR6" },
      { key: "Storage", value: "825GB Custom SSD" },
      { key: "Resolution", value: "Up to 4K at 120fps" },
      { key: "Optical Drive", value: "4K UHD Blu-ray" },
      { key: "Dimensions", value: "15.4 x 10.2 x 4.1 inches" },
      { key: "Weight", value: "9.9 lbs" },
    ],
    tags: ["playstation", "ps5", "console", "gaming", "4k", "next-gen"],
    mainImage: `${IMG}/photo-1606144042614-b2417e99c4e3?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop&q=80`, alt: "PS5 Console Front" },
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "PS5 Console Side" },
      { url: `${IMG}/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop&q=80`, alt: "PS5 Console Back" },
    ],
    imageTransition: "fade",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.9,
    reviewCount: 2847,
    views: 15234,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps5-digital",
    name: "PlayStation 5 Digital Edition",
    slug: "playstation-5-digital-edition",
    category: demoPSCategories[0],
    brand: "Sony",
    price: 449.99,
    salePrice: 429.99,
    discountPercentage: 4,
    stockQuantity: 28,
    sku: "SONY-PS5-DIGI",
    description:
      "Go all digital with the PS5 Digital Edition. Enjoy a sleeker console design with the same powerful features as the disc version, perfect for those who prefer digital game libraries.",
    shortDescription: "All-digital PS5 console for digital game libraries",
    specifications: [
      { key: "CPU", value: "AMD Zen 2, 8 cores at 3.5GHz" },
      { key: "GPU", value: "AMD RDNA 2, 10.28 TFLOPS" },
      { key: "RAM", value: "16GB GDDR6" },
      { key: "Storage", value: "825GB Custom SSD" },
      { key: "Resolution", value: "Up to 4K at 120fps" },
      { key: "Optical Drive", value: "None (Digital Only)" },
      { key: "Dimensions", value: "15.4 x 10.2 x 3.6 inches" },
      { key: "Weight", value: "8.6 lbs" },
    ],
    tags: ["playstation", "ps5", "console", "digital", "4k", "next-gen"],
    mainImage: `${IMG}/photo-1606144042614-b2417e99c4e3?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop&q=80`, alt: "PS5 Digital Edition Front" },
      { url: `${IMG}/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop&q=80`, alt: "PS5 Digital Edition Angled" },
    ],
    imageTransition: "zoom",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.8,
    reviewCount: 1523,
    views: 9876,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps5-slim-disc",
    name: "PlayStation 5 Slim (Disc Edition)",
    slug: "playstation-5-slim-disc",
    category: demoPSCategories[1],
    brand: "Sony",
    price: 499.99,
    salePrice: 479.99,
    discountPercentage: 4,
    stockQuantity: 42,
    sku: "SONY-PS5SL-DISC",
    description:
      "The slimmest PS5 console ever. Features a smaller form factor with 1TB SSD storage, detachable disc drive, and all the same powerful features as the original PS5.",
    shortDescription: "Slimmest PS5 with 1TB storage and detachable disc drive",
    specifications: [
      { key: "CPU", value: "AMD Zen 2, 8 cores at 3.5GHz" },
      { key: "GPU", value: "AMD RDNA 2, 10.28 TFLOPS" },
      { key: "RAM", value: "16GB GDDR6" },
      { key: "Storage", value: "1TB Custom SSD" },
      { key: "Resolution", value: "Up to 4K at 120fps" },
      { key: "Optical Drive", value: "4K UHD Blu-ray (Detachable)" },
      { key: "Dimensions", value: "14.1 x 8.3 x 3.8 inches" },
      { key: "Weight", value: "7.5 lbs" },
    ],
    tags: ["playstation", "ps5", "slim", "console", "gaming", "4k"],
    mainImage: `${IMG}/photo-1621259182978-fbf93132d53d?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "PS5 Slim Front" },
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "PS5 Slim Side" },
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "PS5 Slim Back" },
    ],
    imageTransition: "slide",
    isFeatured: true,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    isActive: true,
    isOutOfStock: false,
    rating: 4.9,
    reviewCount: 456,
    views: 8923,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps5-pro",
    name: "PlayStation 5 Pro",
    slug: "playstation-5-pro",
    category: demoPSCategories[2],
    brand: "Sony",
    price: 599.99,
    salePrice: 579.99,
    discountPercentage: 3,
    stockQuantity: 20,
    sku: "SONY-PS5PRO",
    description:
      "The most powerful PlayStation console ever. Features an enhanced GPU with 67% more compute units, advanced ray tracing, and AI-driven upscaling for stunning 4K visuals at up to 120fps.",
    shortDescription: "Most powerful PS5 with enhanced GPU and AI upscaling",
    specifications: [
      { key: "CPU", value: "AMD Zen 2, 8 cores at 3.85GHz" },
      { key: "GPU", value: "AMD RDNA 2, 16.7 TFLOPS" },
      { key: "RAM", value: "16GB GDDR6" },
      { key: "Storage", value: "2TB Custom SSD" },
      { key: "Resolution", value: "Up to 4K at 120fps, 8K support" },
      { key: "Ray Tracing", value: "Enhanced RT with AI upscaling" },
      { key: "Optical Drive", value: "4K UHD Blu-ray (Sold Separately)" },
      { key: "Dimensions", value: "15.4 x 10.2 x 4.1 inches" },
    ],
    tags: ["playstation", "ps5", "pro", "console", "gaming", "4k", "8k", "premium"],
    mainImage: `${IMG}/photo-1606144042614-b2417e99c4e3?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop&q=80`, alt: "PS5 Pro Front" },
      { url: `${IMG}/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop&q=80`, alt: "PS5 Pro Angled" },
    ],
    imageTransition: "flip",
    isFeatured: true,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    isActive: true,
    isOutOfStock: false,
    rating: 4.8,
    reviewCount: 189,
    views: 12456,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps4-pro",
    name: "PlayStation 4 Pro 1TB Console",
    slug: "playstation-4-pro-1tb",
    category: demoPSCategories[3],
    brand: "Sony",
    price: 349.99,
    salePrice: 299.99,
    discountPercentage: 14,
    stockQuantity: 55,
    sku: "SONY-PS4PRO-1TB",
    description:
      "Experience enhanced gaming with the PS4 Pro. Featuring 4K HDR gaming, faster frame rates, and a massive library of games. Perfect for gamers who want an affordable 4K gaming experience.",
    shortDescription: "Enhanced PS4 with 4K HDR gaming at an affordable price",
    specifications: [
      { key: "CPU", value: "AMD Jaguar, 8 cores at 2.13GHz" },
      { key: "GPU", value: "AMD Radeon, 4.2 TFLOPS" },
      { key: "RAM", value: "8GB GDDR5" },
      { key: "Storage", value: "1TB HDD" },
      { key: "Resolution", value: "Up to 4K (upscaled)" },
      { key: "HDR", value: "Yes" },
      { key: "Optical Drive", value: "Blu-ray / DVD" },
      { key: "Dimensions", value: "11.6 x 2.1 x 12.9 inches" },
    ],
    tags: ["playstation", "ps4", "pro", "console", "4k", "hdr", "affordable"],
    mainImage: `${IMG}/photo-1606144042614-b2417e99c4e3?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop&q=80`, alt: "PS4 Pro Front" },
      { url: `${IMG}/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop&q=80`, alt: "PS4 Pro Back" },
    ],
    imageTransition: "fade",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.7,
    reviewCount: 1823,
    views: 7654,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps4-slim",
    name: "PlayStation 4 Slim 500GB Console",
    slug: "playstation-4-slim-500gb",
    category: demoPSCategories[4],
    brand: "Sony",
    price: 299.99,
    salePrice: 249.99,
    discountPercentage: 17,
    stockQuantity: 68,
    sku: "SONY-PS4SLIM-500",
    description:
      "Sleek and compact PS4 with all the features you love. Perfect entry point into the PlayStation ecosystem with a vast library of games available.",
    shortDescription: "Compact PS4 with 500GB storage for entry-level gaming",
    specifications: [
      { key: "CPU", value: "AMD Jaguar, 8 cores at 1.6GHz" },
      { key: "GPU", value: "AMD Radeon, 1.84 TFLOPS" },
      { key: "RAM", value: "8GB GDDR5" },
      { key: "Storage", value: "500GB HDD" },
      { key: "Resolution", value: "Up to 1080p" },
      { key: "HDR", value: "Yes" },
      { key: "Optical Drive", value: "Blu-ray / DVD" },
      { key: "Dimensions", value: "11.3 x 1.5 x 10.4 inches" },
    ],
    tags: ["playstation", "ps4", "slim", "console", "1080p", "affordable"],
    mainImage: `${IMG}/photo-1606144042614-b2417e99c4e3?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop&q=80`, alt: "PS4 Slim Front" },
      { url: `${IMG}/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop&q=80`, alt: "PS4 Slim Top" },
    ],
    imageTransition: "slide",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.6,
    reviewCount: 2341,
    views: 6543,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-psvr2",
    name: "PlayStation VR2 Headset",
    slug: "playstation-vr2-headset",
    category: demoPSCategories[5],
    brand: "Sony",
    price: 549.99,
    salePrice: 499.99,
    discountPercentage: 9,
    stockQuantity: 15,
    sku: "SONY-PSVR2",
    description:
      "Immerse yourself in next-gen virtual reality with PlayStation VR2. Features 4K HDR OLED displays, eye tracking, haptic feedback, and Tempest 3D AudioTech for truly immersive experiences.",
    shortDescription: "Next-gen VR headset with 4K HDR OLED and eye tracking",
    specifications: [
      { key: "Display", value: "4K HDR OLED (2000x2040 per eye)" },
      { key: "Refresh Rate", value: "90Hz / 120Hz" },
      { key: "Field of View", value: "110 degrees" },
      { key: "Tracking", value: "Inside-out 6DoF" },
      { key: "Eye Tracking", value: "Yes" },
      { key: "Haptic Feedback", value: "Yes (Headset and Controllers)" },
      { key: "Audio", value: "Tempest 3D AudioTech" },
      { key: "Weight", value: "1.1 lbs" },
    ],
    tags: ["playstation", "vr", "virtual reality", "headset", "immersive"],
    mainImage: `${IMG}/photo-1622979135225-d2ba269cf1ac?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1622979135225-d2ba269cf1ac?w=600&h=600&fit=crop&q=80`, alt: "PSVR2 Front" },
      { url: `${IMG}/photo-1622979135225-d2ba269cf1ac?w=600&h=600&fit=crop&q=80`, alt: "PSVR2 Side" },
      { url: `${IMG}/photo-1622979135225-d2ba269cf1ac?w=600&h=600&fit=crop&q=80`, alt: "PSVR2 Wearing" },
    ],
    imageTransition: "zoom",
    isFeatured: true,
    isTrending: false,
    isNewArrival: true,
    isBestSeller: false,
    isActive: true,
    isOutOfStock: false,
    rating: 4.7,
    reviewCount: 892,
    views: 5432,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-dualsense-white",
    name: "DualSense Wireless Controller (White)",
    slug: "dualsense-wireless-controller-white",
    category: demoPSCategories[8],
    brand: "Sony",
    price: 79.99,
    salePrice: 69.99,
    discountPercentage: 13,
    stockQuantity: 120,
    sku: "SONY-DS-WHITE",
    description:
      "Discover a deeper, more immersive gaming experience with the DualSense wireless controller. Features haptic feedback, adaptive triggers, and a built-in microphone.",
    shortDescription: "Next-gen controller with haptic feedback and adaptive triggers",
    specifications: [
      { key: "Connectivity", value: "Bluetooth 5.1, USB-C" },
      { key: "Battery", value: "1560mAh rechargeable" },
      { key: "Battery Life", value: "Up to 12 hours" },
      { key: "Haptic Feedback", value: "Yes" },
      { key: "Adaptive Triggers", value: "Yes" },
      { key: "Built-in Microphone", value: "Yes" },
      { key: "Touchpad", value: "Yes" },
      { key: "Weight", value: "9.9 oz" },
    ],
    tags: ["controller", "wireless", "dualsense", "playstation", "ps5"],
    mainImage: `${IMG}/photo-1592840496694-26d035b52b48?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1592840496694-26d035b52b48?w=600&h=600&fit=crop&q=80`, alt: "DualSense Front" },
      { url: `${IMG}/photo-1592840496694-26d035b52b48?w=600&h=600&fit=crop&q=80`, alt: "DualSense Back" },
    ],
    imageTransition: "fade",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.8,
    reviewCount: 1567,
    views: 8765,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-dualsense-midnight",
    name: "DualSense Wireless Controller (Midnight Black)",
    slug: "dualsense-wireless-controller-midnight-black",
    category: demoPSCategories[8],
    brand: "Sony",
    price: 79.99,
    salePrice: 74.99,
    discountPercentage: 6,
    stockQuantity: 95,
    sku: "SONY-DS-BLACK",
    description:
      "Sleek midnight black DualSense controller with all the same innovative features. The perfect companion for your PS5 console.",
    shortDescription: "Midnight black DualSense with haptic feedback",
    specifications: [
      { key: "Connectivity", value: "Bluetooth 5.1, USB-C" },
      { key: "Battery", value: "1560mAh rechargeable" },
      { key: "Battery Life", value: "Up to 12 hours" },
      { key: "Haptic Feedback", value: "Yes" },
      { key: "Adaptive Triggers", value: "Yes" },
      { key: "Built-in Microphone", value: "Yes" },
      { key: "Color", value: "Midnight Black" },
      { key: "Weight", value: "9.9 oz" },
    ],
    tags: ["controller", "wireless", "dualsense", "playstation", "ps5", "black"],
    mainImage: `${IMG}/photo-1592840496694-26d035b52b48?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1592840496694-26d035b52b48?w=600&h=600&fit=crop&q=80`, alt: "DualSense Black Front" },
      { url: `${IMG}/photo-1592840496694-26d035b52b48?w=600&h=600&fit=crop&q=80`, alt: "DualSense Black Back" },
    ],
    imageTransition: "fade",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.8,
    reviewCount: 1234,
    views: 6543,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps5-bundle-spiderman",
    name: "PlayStation 5 Slim Bundle with Marvel's Spider-Man 2",
    slug: "ps5-slim-bundle-spider-man-2",
    category: demoPSCategories[9],
    brand: "Sony",
    price: 559.99,
    salePrice: 529.99,
    discountPercentage: 5,
    stockQuantity: 18,
    sku: "SONY-PS5SL-SPDRMN",
    description:
      "Get the PS5 Slim console plus Marvel's Spider-Man 2 digital voucher. Experience the incredible Spider-Man adventure with enhanced graphics and performance.",
    shortDescription: "PS5 Slim console with Marvel's Spider-Man 2 game",
    specifications: [
      { key: "Console", value: "PS5 Slim (Disc Edition)" },
      { key: "Game Included", value: "Marvel's Spider-Man 2 (Digital)" },
      { key: "Storage", value: "1TB SSD" },
      { key: "Controller", value: "DualSense Wireless (White)" },
      { key: "Resolution", value: "Up to 4K at 120fps" },
      { key: "Extras", value: "HDMI Cable, AC Cord, USB Cable" },
    ],
    tags: ["bundle", "playstation", "ps5", "slim", "spider-man", "game"],
    mainImage: `${IMG}/photo-1621259182978-fbf93132d53d?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "PS5 Slim Bundle Front" },
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Bundle Contents" },
      { url: `${IMG}/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop&q=80`, alt: "Bundle Side" },
    ],
    imageTransition: "slide",
    isFeatured: true,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    isActive: true,
    isOutOfStock: false,
    rating: 4.9,
    reviewCount: 345,
    views: 7890,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps5-charging-station",
    name: "DualSense Charging Station",
    slug: "dualsense-charging-station",
    category: demoPSCategories[7],
    brand: "Sony",
    price: 29.99,
    salePrice: 24.99,
    discountPercentage: 17,
    stockQuantity: 85,
    sku: "SONY-DS-CHARGE",
    description:
      "Charge up to two DualSense wireless controllers simultaneously without connecting to your PS5 console. Click-in design makes charging easy and convenient.",
    shortDescription: "Charge two DualSense controllers simultaneously",
    specifications: [
      { key: "Compatibility", value: "DualSense Wireless Controller" },
      { key: "Capacity", value: "2 Controllers" },
      { key: "Charging Time", value: "Approx. 3 hours" },
      { key: "Power", value: "USB-C (AC adapter included)" },
      { key: "Design", value: "Click-in docking" },
      { key: "LED Indicators", value: "Yes" },
    ],
    tags: ["accessory", "charging", "dualsense", "playstation", "ps5"],
    mainImage: `${IMG}/photo-1592840496694-26d035b52b48?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1592840496694-26d035b52b48?w=600&h=600&fit=crop&q=80`, alt: "Charging Station Front" },
      { url: `${IMG}/photo-1592840496694-26d035b52b48?w=600&h=600&fit=crop&q=80`, alt: "Charging Station with Controllers" },
    ],
    imageTransition: "zoom",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.6,
    reviewCount: 876,
    views: 3456,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-ps5-refurbished",
    name: "Refurbished PlayStation 5 Console (Disc Edition)",
    slug: "refurbished-playstation-5-disc",
    category: demoPSCategories[10],
    brand: "Sony",
    price: 449.99,
    salePrice: 399.99,
    discountPercentage: 11,
    stockQuantity: 25,
    sku: "SONY-PS5-REFB",
    description:
      "Certified refurbished PS5 console tested to meet original factory specifications. Includes 90-day warranty. Looks and performs like new at a fraction of the cost.",
    shortDescription: "Certified refurbished PS5 with 90-day warranty",
    specifications: [
      { key: "Condition", value: "Certified Refurbished" },
      { key: "CPU", value: "AMD Zen 2, 8 cores at 3.5GHz" },
      { key: "GPU", value: "AMD RDNA 2, 10.28 TFLOPS" },
      { key: "RAM", value: "16GB GDDR6" },
      { key: "Storage", value: "825GB Custom SSD" },
      { key: "Warranty", value: "90-Day Manufacturer Warranty" },
      { key: "Includes", value: "Console, DualSense, HDMI, Power Cable" },
      { key: "Testing", value: "Full factory diagnostic testing" },
    ],
    tags: ["refurbished", "playstation", "ps5", "console", "value", "warranty"],
    mainImage: `${IMG}/photo-1606144042614-b2417e99c4e3?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop&q=80`, alt: "Refurbished PS5 Front" },
      { url: `${IMG}/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop&q=80`, alt: "Refurbished PS5 Back" },
    ],
    imageTransition: "fade",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    isActive: true,
    isOutOfStock: false,
    rating: 4.5,
    reviewCount: 432,
    views: 2345,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// ─── Xbox Products ───────────────────────────────────────────────────────────

export const demoXboxProducts: Product[] = [
  {
    _id: "demo-xbox-series-x",
    name: "Xbox Series X Console (1TB)",
    slug: "xbox-series-x-1tb",
    category: demoXboxCategories[0],
    brand: "Microsoft",
    price: 499.99,
    salePrice: 479.99,
    discountPercentage: 4,
    stockQuantity: 38,
    sku: "MS-XSX-1TB",
    description:
      "The fastest, most powerful Xbox ever. Play thousands of games from four generations with 12 teraflops of GPU power, 4K gaming at up to 120fps, and Quick Resume.",
    shortDescription: "Most powerful Xbox with 12TF GPU and 4K at 120fps",
    specifications: [
      { key: "CPU", value: "AMD Zen 2, 8 cores at 3.8GHz (3.6GHz w/ SMT)" },
      { key: "GPU", value: "AMD RDNA 2, 12 TFLOPS, 52 CUs" },
      { key: "RAM", value: "16GB GDDR6" },
      { key: "Storage", value: "1TB Custom NVMe SSD" },
      { key: "Resolution", value: "Up to 4K at 120fps, 8K support" },
      { key: "Optical Drive", value: "4K UHD Blu-ray" },
      { key: "Dimensions", value: "11.9 x 5.9 x 5.9 inches" },
      { key: "Weight", value: "9.5 lbs" },
    ],
    tags: ["xbox", "series x", "console", "gaming", "4k", "next-gen"],
    mainImage: `${IMG}/photo-1621259182978-fbf93132d53d?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Xbox Series X Front" },
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Xbox Series X Top" },
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Xbox Series X Back" },
    ],
    imageTransition: "fade",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.8,
    reviewCount: 2156,
    views: 13456,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-series-s",
    name: "Xbox Series S Console (512GB)",
    slug: "xbox-series-s-512gb",
    category: demoXboxCategories[1],
    brand: "Microsoft",
    price: 299.99,
    salePrice: 279.99,
    discountPercentage: 7,
    stockQuantity: 52,
    sku: "MS-XSS-512",
    description:
      "Next-gen performance in the smallest Xbox ever. Experience 1440p gaming at up to 120fps, digital-only design, and all the same next-gen features as Series X.",
    shortDescription: "Smallest Xbox with 1440p gaming and digital-only design",
    specifications: [
      { key: "CPU", value: "AMD Zen 2, 8 cores at 3.6GHz (3.4GHz w/ SMT)" },
      { key: "GPU", value: "AMD RDNA 2, 4 TFLOPS, 20 CUs" },
      { key: "RAM", value: "10GB GDDR6" },
      { key: "Storage", value: "512GB Custom NVMe SSD" },
      { key: "Resolution", value: "Up to 1440p at 120fps, 4K upscale" },
      { key: "Optical Drive", value: "None (Digital Only)" },
      { key: "Dimensions", value: "11.3 x 2.6 x 5.9 inches" },
      { key: "Weight", value: "4.2 lbs" },
    ],
    tags: ["xbox", "series s", "console", "gaming", "1440p", "digital"],
    mainImage: `${IMG}/photo-1621259182978-fbf93132d53d?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Xbox Series S Front" },
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Xbox Series S Side" },
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Xbox Series S Back" },
    ],
    imageTransition: "slide",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.7,
    reviewCount: 1892,
    views: 11234,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-one-x",
    name: "Xbox One X 1TB Console",
    slug: "xbox-one-x-1tb",
    category: demoXboxCategories[2],
    brand: "Microsoft",
    price: 399.99,
    salePrice: 349.99,
    discountPercentage: 13,
    stockQuantity: 30,
    sku: "MS-XBOX1X-1TB",
    description:
      "The world's most powerful console with true 4K gaming. Experience enhanced graphics, faster load times, and a massive library of games.",
    shortDescription: "True 4K gaming with 6TF GPU and HDR support",
    specifications: [
      { key: "CPU", value: "AMD Jaguar, 8 cores at 2.3GHz" },
      { key: "GPU", value: "AMD Radeon, 6 TFLOPS, 40 CUs" },
      { key: "RAM", value: "12GB GDDR5" },
      { key: "Storage", value: "1TB HDD" },
      { key: "Resolution", value: "Up to 4K (native)" },
      { key: "HDR", value: "Yes" },
      { key: "Optical Drive", value: "4K UHD Blu-ray" },
      { key: "Dimensions", value: "11.8 x 9.4 x 2.6 inches" },
    ],
    tags: ["xbox", "one x", "console", "4k", "hdr", "gaming"],
    mainImage: `${IMG}/photo-1621259182978-fbf93132d53d?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Xbox One X Front" },
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Xbox One X Back" },
    ],
    imageTransition: "fade",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    isActive: true,
    isOutOfStock: false,
    rating: 4.6,
    reviewCount: 1234,
    views: 5678,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-one-s",
    name: "Xbox One S 1TB Console",
    slug: "xbox-one-s-1tb",
    category: demoXboxCategories[3],
    brand: "Microsoft",
    price: 299.99,
    salePrice: 269.99,
    discountPercentage: 10,
    stockQuantity: 45,
    sku: "MS-XBOX1S-1TB",
    description:
      "Sleek design with 4K Ultra HD and HDR gaming. The perfect all-in-one entertainment system with a compact form factor.",
    shortDescription: "Compact 4K HDR console for entertainment and gaming",
    specifications: [
      { key: "CPU", value: "AMD Jaguar, 8 cores at 1.75GHz" },
      { key: "GPU", value: "AMD Radeon, 1.4 TFLOPS, 12 CUs" },
      { key: "RAM", value: "8GB GDDR3" },
      { key: "Storage", value: "1TB HDD" },
      { key: "Resolution", value: "Up to 4K (upscaled), 1080p native" },
      { key: "HDR", value: "Yes" },
      { key: "Optical Drive", value: "Blu-ray / DVD" },
      { key: "Dimensions", value: "11.6 x 8.9 x 2.5 inches" },
    ],
    tags: ["xbox", "one s", "console", "4k", "hdr", "compact"],
    mainImage: `${IMG}/photo-1621259182978-fbf93132d53d?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Xbox One S Front" },
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Xbox One S Side" },
    ],
    imageTransition: "slide",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.5,
    reviewCount: 1567,
    views: 4567,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-one",
    name: "Xbox One 500GB Console",
    slug: "xbox-one-500gb",
    category: demoXboxCategories[4],
    brand: "Microsoft",
    price: 249.99,
    salePrice: 199.99,
    discountPercentage: 20,
    stockQuantity: 40,
    sku: "MS-XBOX1-500",
    description:
      "The original Xbox One with a massive library of games. Great entry point for new gamers with Xbox Game Pass compatibility.",
    shortDescription: "Original Xbox One with 500GB storage and Game Pass support",
    specifications: [
      { key: "CPU", value: "AMD Jaguar, 8 cores at 1.75GHz" },
      { key: "GPU", value: "AMD Radeon, 1.31 TFLOPS" },
      { key: "RAM", value: "8GB DDR3" },
      { key: "Storage", value: "500GB HDD" },
      { key: "Resolution", value: "Up to 1080p" },
      { key: "HDR", value: "No" },
      { key: "Optical Drive", value: "Blu-ray / DVD" },
      { key: "Dimensions", value: "13.1 x 10.8 x 3.2 inches" },
    ],
    tags: ["xbox", "one", "console", "1080p", "affordable", "entry-level"],
    mainImage: `${IMG}/photo-1621259182978-fbf93132d53d?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Xbox One Front" },
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Xbox One Back" },
    ],
    imageTransition: "fade",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    isActive: true,
    isOutOfStock: false,
    rating: 4.3,
    reviewCount: 987,
    views: 3456,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-controller-black",
    name: "Xbox Wireless Controller (Carbon Black)",
    slug: "xbox-wireless-controller-carbon-black",
    category: demoXboxCategories[5],
    brand: "Microsoft",
    price: 69.99,
    salePrice: 59.99,
    discountPercentage: 14,
    stockQuantity: 150,
    sku: "MS-XBOX-CTRL-BLK",
    description:
      "Experience the modernized design of the Xbox Wireless Controller with textured grip, improved ergonomics, and share button for capturing gameplay.",
    shortDescription: "Modernized Xbox controller with textured grip and share button",
    specifications: [
      { key: "Connectivity", value: "Bluetooth 5.0, Xbox Wireless" },
      { key: "Battery", value: "AA batteries or USB-C rechargeable (sold separately)" },
      { key: "Battery Life", value: "Up to 40 hours" },
      { key: "Compatibility", value: "Xbox Series X|S, Xbox One, PC, iOS, Android" },
      { key: "Share Button", value: "Yes" },
      { key: "Textured Grip", value: "Yes" },
      { key: "USB-C Port", value: "Yes" },
      { key: "Weight", value: "9.9 oz" },
    ],
    tags: ["controller", "wireless", "xbox", "bluetooth", "carbon-black"],
    mainImage: `${IMG}/photo-1592840496694-26d035b52b48?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1592840496694-26d035b52b48?w=600&h=600&fit=crop&q=80`, alt: "Xbox Controller Front" },
      { url: `${IMG}/photo-1592840496694-26d035b52b48?w=600&h=600&fit=crop&q=80`, alt: "Xbox Controller Back" },
    ],
    imageTransition: "fade",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.8,
    reviewCount: 2345,
    views: 9876,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-controller-robot",
    name: "Xbox Wireless Controller (Robot White)",
    slug: "xbox-wireless-controller-robot-white",
    category: demoXboxCategories[5],
    brand: "Microsoft",
    price: 69.99,
    salePrice: 64.99,
    discountPercentage: 7,
    stockQuantity: 110,
    sku: "MS-XBOX-CTRL-WHT",
    description:
      "Clean robot white design with all the same features as the standard Xbox Wireless Controller. Perfect match for Xbox Series S.",
    shortDescription: "Robot white Xbox controller for Series S and beyond",
    specifications: [
      { key: "Connectivity", value: "Bluetooth 5.0, Xbox Wireless" },
      { key: "Battery", value: "AA batteries or USB-C rechargeable (sold separately)" },
      { key: "Battery Life", value: "Up to 40 hours" },
      { key: "Compatibility", value: "Xbox Series X|S, Xbox One, PC, iOS, Android" },
      { key: "Share Button", value: "Yes" },
      { key: "Color", value: "Robot White" },
      { key: "USB-C Port", value: "Yes" },
      { key: "Weight", value: "9.9 oz" },
    ],
    tags: ["controller", "wireless", "xbox", "white", "robot-white"],
    mainImage: `${IMG}/photo-1592840496694-26d035b52b48?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1592840496694-26d035b52b48?w=600&h=600&fit=crop&q=80`, alt: "Xbox Controller White Front" },
      { url: `${IMG}/photo-1592840496694-26d035b52b48?w=600&h=600&fit=crop&q=80`, alt: "Xbox Controller White Back" },
    ],
    imageTransition: "fade",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.7,
    reviewCount: 1567,
    views: 6543,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-elite-2",
    name: "Xbox Elite Wireless Controller Series 2",
    slug: "xbox-elite-wireless-controller-series-2",
    category: demoXboxCategories[5],
    brand: "Microsoft",
    price: 179.99,
    salePrice: 159.99,
    discountPercentage: 11,
    stockQuantity: 22,
    sku: "MS-XBOX-ELITE2",
    description:
      "The pro-level controller for serious gamers. Features shorter hair trigger locks, wrap-around rubberized grip, and up to 40 hours of battery life.",
    shortDescription: "Pro-level controller with shorter hair triggers and rubberized grip",
    specifications: [
      { key: "Connectivity", value: "Bluetooth 5.0, Xbox Wireless" },
      { key: "Battery Life", value: "Up to 40 hours" },
      { key: "Adjustable Tension", value: "Yes (thumbsticks)" },
      { key: "Hair Trigger Locks", value: "Yes (shorter)" },
      { key: "Wrap-around Grip", value: "Yes (rubberized)" },
      { key: "Custom Profiles", value: "Up to 3" },
      { key: "Compatibility", value: "Xbox Series X|S, Xbox One, PC" },
      { key: "Weight", value: "12.6 oz" },
    ],
    tags: ["controller", "elite", "wireless", "xbox", "pro", "premium"],
    mainImage: `${IMG}/photo-1592840496694-26d035b52b48?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1592840496694-26d035b52b48?w=600&h=600&fit=crop&q=80`, alt: "Elite Controller Front" },
      { url: `${IMG}/photo-1592840496694-26d035b52b48?w=600&h=600&fit=crop&q=80`, alt: "Elite Controller Back" },
      { url: `${IMG}/photo-1592840496694-26d035b52b48?w=600&h=600&fit=crop&q=80`, alt: "Elite Controller Case" },
    ],
    imageTransition: "zoom",
    isFeatured: true,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    isActive: true,
    isOutOfStock: false,
    rating: 4.7,
    reviewCount: 876,
    views: 4567,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-headset",
    name: "Xbox Stereo Headset",
    slug: "xbox-stereo-headset",
    category: demoXboxCategories[6],
    brand: "Microsoft",
    price: 59.99,
    salePrice: 49.99,
    discountPercentage: 17,
    stockQuantity: 65,
    sku: "MS-XBOX-HDS",
    description:
      "Enjoy game audio and chat with the Xbox Stereo Headset. Features lightweight design, soft ear cushions, and a flexible boom mic.",
    shortDescription: "Lightweight stereo headset with flexible boom mic",
    specifications: [
      { key: "Type", value: "Over-ear, wired" },
      { key: "Connection", value: "3.5mm audio jack" },
      { key: "Microphone", value: "Flexible boom mic" },
      { key: "Frequency Response", value: "20Hz - 20kHz" },
      { key: "Impedance", value: "32 ohms" },
      { key: "Compatibility", value: "Xbox Series X|S, Xbox One, PC, Mobile" },
      { key: "Ear Cushions", value: "Soft, breathable fabric" },
      { key: "Weight", value: "8.5 oz" },
    ],
    tags: ["headset", "audio", "xbox", "wired", "affordable"],
    mainImage: `${IMG}/photo-1583394838336-acd977736f90?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1583394838336-acd977736f90?w=600&h=600&fit=crop&q=80`, alt: "Xbox Headset Front" },
      { url: `${IMG}/photo-1583394838336-acd977736f90?w=600&h=600&fit=crop&q=80`, alt: "Xbox Headset Side" },
    ],
    imageTransition: "fade",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.5,
    reviewCount: 1234,
    views: 5678,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-series-x-bundle",
    name: "Xbox Series X Bundle with Forza Horizon 5",
    slug: "xbox-series-x-bundle-forza-horizon-5",
    category: demoXboxCategories[7],
    brand: "Microsoft",
    price: 549.99,
    salePrice: 519.99,
    discountPercentage: 5,
    stockQuantity: 22,
    sku: "MS-XSX-FORZA",
    description:
      "Get the Xbox Series X console plus Forza Horizon 5 Standard Edition. Experience the ultimate racing game in stunning 4K.",
    shortDescription: "Xbox Series X console with Forza Horizon 5 game",
    specifications: [
      { key: "Console", value: "Xbox Series X (1TB)" },
      { key: "Game Included", value: "Forza Horizon 5 (Digital)" },
      { key: "Storage", value: "1TB Custom NVMe SSD" },
      { key: "Controller", value: "Xbox Wireless (Carbon Black)" },
      { key: "Resolution", value: "Up to 4K at 120fps" },
      { key: "Extras", value: "HDMI Cable, Power Cable" },
    ],
    tags: ["bundle", "xbox", "series x", "forza", "racing", "game"],
    mainImage: `${IMG}/photo-1621259182978-fbf93132d53d?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Xbox Series X Bundle Front" },
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Bundle Contents" },
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Bundle Side" },
    ],
    imageTransition: "slide",
    isFeatured: true,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    isActive: true,
    isOutOfStock: false,
    rating: 4.8,
    reviewCount: 567,
    views: 8901,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-play-charge",
    name: "Xbox Rechargeable Battery Pack + USB-C Cable",
    slug: "xbox-rechargeable-battery-pack",
    category: demoXboxCategories[6],
    brand: "Microsoft",
    price: 24.99,
    salePrice: 19.99,
    discountPercentage: 20,
    stockQuantity: 95,
    sku: "MS-XBOX-BATT",
    description:
      "Keep your Xbox controller charged and ready. Features a rechargeable battery pack that provides up to 30 hours of gameplay.",
    shortDescription: "Rechargeable battery pack with 30-hour battery life",
    specifications: [
      { key: "Compatibility", value: "Xbox Series X|S, Xbox One controllers" },
      { key: "Battery Life", value: "Up to 30 hours" },
      { key: "Charging Time", value: "Approx. 4 hours" },
      { key: "Connection", value: "USB-C cable included" },
      { key: "LED Indicator", value: "Yes" },
      { key: "Includes", value: "Battery pack, USB-C cable (3m)" },
    ],
    tags: ["accessory", "battery", "rechargeable", "xbox", "charging"],
    mainImage: `${IMG}/photo-1592840496694-26d035b52b48?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1592840496694-26d035b52b48?w=600&h=600&fit=crop&q=80`, alt: "Battery Pack Front" },
      { url: `${IMG}/photo-1592840496694-26d035b52b48?w=600&h=600&fit=crop&q=80`, alt: "Battery Pack with Controller" },
    ],
    imageTransition: "zoom",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    isOutOfStock: false,
    rating: 4.6,
    reviewCount: 1456,
    views: 4321,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "demo-xbox-refurbished",
    name: "Refurbished Xbox Series S Console (512GB)",
    slug: "refurbished-xbox-series-s-512gb",
    category: demoXboxCategories[8],
    brand: "Microsoft",
    price: 249.99,
    salePrice: 219.99,
    discountPercentage: 12,
    stockQuantity: 30,
    sku: "MS-XSS-REFB",
    description:
      "Certified refurbished Xbox Series S console tested to meet original factory specifications. Includes 90-day warranty. Perfect entry into next-gen gaming.",
    shortDescription: "Certified refurbished Series S with 90-day warranty",
    specifications: [
      { key: "Condition", value: "Certified Refurbished" },
      { key: "CPU", value: "AMD Zen 2, 8 cores at 3.6GHz (3.4GHz w/ SMT)" },
      { key: "GPU", value: "AMD RDNA 2, 4 TFLOPS, 20 CUs" },
      { key: "RAM", value: "10GB GDDR6" },
      { key: "Storage", value: "512GB Custom NVMe SSD" },
      { key: "Warranty", value: "90-Day Manufacturer Warranty" },
      { key: "Includes", value: "Console, Controller, HDMI, Power Cable" },
      { key: "Testing", value: "Full factory diagnostic testing" },
    ],
    tags: ["refurbished", "xbox", "series s", "console", "value", "warranty"],
    mainImage: `${IMG}/photo-1621259182978-fbf93132d53d?w=900&h=900&fit=crop&q=80`,
    galleryImages: [
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Refurbished Series S Front" },
      { url: `${IMG}/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop&q=80`, alt: "Refurbished Series S Back" },
    ],
    imageTransition: "fade",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    isActive: true,
    isOutOfStock: false,
    rating: 4.4,
    reviewCount: 345,
    views: 2109,
    variants: [],
    variantAttributes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];