import fs from "fs";
import path from "path";

function loadEnv() {
  const envPath = path.join(process.cwd(), ".env.local");
  if (!fs.existsSync(envPath)) return;
  const lines = fs.readFileSync(envPath, "utf8").split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const i = trimmed.indexOf("=");
    if (i === -1) continue;
    process.env[trimmed.slice(0, i).trim()] ??= trimmed.slice(i + 1).trim();
  }
}

loadEnv();

import mongoose from "mongoose";
import connectDB from "../lib/mongodb";
import Category from "../models/Category";
import Product from "../models/Product";
import Banner from "../models/Banner";
import Coupon from "../models/Coupon";
import Settings, { DEFAULT_SETTINGS } from "../models/Settings";
import { slugify } from "../lib/utils";

const IMAGES = {
  consoles: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&h=800&fit=crop",
  controllers: "https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=800&h=800&fit=crop",
  headsets: "https://images.unsplash.com/photo-1612444530582-fc66f8ddd681?w=800&h=800&fit=crop",
  keyboards: "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=800&h=800&fit=crop",
  mouse: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=800&h=800&fit=crop",
  games: "https://images.unsplash.com/photo-1556438064-2d7646166914?w=800&h=800&fit=crop",
  monitors: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&h=800&fit=crop",
  chairs: "https://images.unsplash.com/photo-1598550476439-684718afbd15?w=800&h=800&fit=crop",
  switch: "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&h=800&fit=crop",
};

let imgCounter = 0;
function img(base: string, extra?: string) {
  imgCounter++;
  return base + "&t=" + imgCounter + "-" + (extra || Math.random().toString(36).slice(2, 6));
}

interface ProductVariant {
  name: string;
  sku: string;
  price: number;
  salePrice?: number;
  stockQuantity: number;
  attributes: { key: string; value: string }[];
  image?: string;
}

interface ProductDef {
  name: string;
  categorySlug: string;
  brand: string;
  price: number;
  salePrice?: number;
  stockQuantity: number;
  sku: string;
  description: string;
  shortDescription: string;
  mainImage: string;
  galleryImages: { url: string; alt: string }[];
  specifications: { key: string; value: string }[];
  tags: string[];
  isFeatured?: boolean;
  isTrending?: boolean;
  isNewArrival?: boolean;
  isBestSeller?: boolean;
  rating: number;
  reviewCount: number;
  views: number;
  variants?: ProductVariant[];
}

const PRODUCTS: ProductDef[] = [
  // ── Gaming Consoles ──
  {
    name: "Sony PlayStation 5 Console",
    categorySlug: "playstation-5",
    brand: "Sony",
    price: 499.99,
    stockQuantity: 25,
    sku: "RG-CON-0001",
    description: "Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with haptic feedback, adaptive triggers, and 3D Audio.",
    shortDescription: "Next-gen gaming console with 4K gaming and ray tracing",
    mainImage: IMAGES.consoles,
    galleryImages: [
      { url: img(IMAGES.consoles, "g1"), alt: "PS5 Front View" },
      { url: img(IMAGES.consoles, "g2"), alt: "PS5 Side View" },
      { url: img(IMAGES.consoles, "g3"), alt: "PS5 Controller" },
    ],
    specifications: [
      { key: "CPU", value: "AMD Zen 2, 8 cores @ 3.5 GHz" },
      { key: "GPU", value: "AMD RDNA 2, 10.28 TFLOPS" },
      { key: "RAM", value: "16 GB GDDR6" },
      { key: "Storage", value: "825 GB SSD" },
      { key: "Resolution", value: "Up to 4K @ 120fps" },
      { key: "Disc Drive", value: "4K UHD Blu-ray" },
    ],
    tags: ["playstation", "ps5", "console", "4k", "gaming", "sony", "next-gen", "ray-tracing"],
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 189,
    views: 4820,
    variants: [
      { name: "Disc Edition", sku: "RG-CON-0001-D", price: 499.99, stockQuantity: 15, attributes: [{ key: "Edition", value: "Disc" }, { key: "Color", value: "White" }], image: IMAGES.consoles },
      { name: "Digital Edition", sku: "RG-CON-0001-DE", price: 399.99, stockQuantity: 10, attributes: [{ key: "Edition", value: "Digital" }, { key: "Color", value: "White" }], image: img(IMAGES.consoles, "v2") },
    ],
  },
  {
    name: "Sony PlayStation 5 Slim",
    categorySlug: "playstation-5-slim",
    brand: "Sony",
    price: 449.99,
    stockQuantity: 30,
    sku: "RG-CON-0002",
    description: "The PS5 Slim model is smaller, lighter, and comes with a 1TB SSD. Enjoy the same powerful performance in a more compact form factor.",
    shortDescription: "Compact PS5 with 1TB SSD storage",
    mainImage: img(IMAGES.consoles, "slim"),
    galleryImages: [
      { url: img(IMAGES.consoles, "slim-g1"), alt: "PS5 Slim Front" },
      { url: img(IMAGES.consoles, "slim-g2"), alt: "PS5 Slim Side" },
    ],
    specifications: [
      { key: "CPU", value: "AMD Zen 2, 8 cores @ 3.5 GHz" },
      { key: "GPU", value: "AMD RDNA 2, 10.28 TFLOPS" },
      { key: "RAM", value: "16 GB GDDR6" },
      { key: "Storage", value: "1 TB SSD" },
      { key: "Weight", value: "3.2 kg" },
    ],
    tags: ["playstation", "ps5", "slim", "console", "compact", "sony", "1tb"],
    isNewArrival: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 95,
    views: 3200,
    variants: [
      { name: "Disc Edition", sku: "RG-CON-0002-D", price: 449.99, stockQuantity: 18, attributes: [{ key: "Edition", value: "Disc" }, { key: "Color", value: "White" }] },
      { name: "Digital Edition", sku: "RG-CON-0002-DE", price: 399.99, stockQuantity: 12, attributes: [{ key: "Edition", value: "Digital" }, { key: "Color", value: "White" }] },
    ],
  },
  {
    name: "Sony PlayStation 5 Pro",
    categorySlug: "playstation-5-pro",
    brand: "Sony",
    price: 599.99,
    stockQuantity: 15,
    sku: "RG-CON-0003",
    description: "The most powerful PlayStation console ever. Enhanced GPU delivers native 4K gaming at 120fps, with advanced ray tracing and AI-driven upscaling.",
    shortDescription: "Most powerful PS5 with enhanced GPU and 4K@120fps",
    mainImage: img(IMAGES.consoles, "pro"),
    galleryImages: [
      { url: img(IMAGES.consoles, "pro-g1"), alt: "PS5 Pro Front" },
      { url: img(IMAGES.consoles, "pro-g2"), alt: "PS5 Pro Back" },
      { url: img(IMAGES.consoles, "pro-g3"), alt: "PS5 Pro Detail" },
    ],
    specifications: [
      { key: "CPU", value: "AMD Zen 2, 8 cores @ 3.85 GHz" },
      { key: "GPU", value: "AMD RDNA 3, 16.7 TFLOPS" },
      { key: "RAM", value: "16 GB GDDR6" },
      { key: "Storage", value: "2 TB SSD" },
      { key: "Resolution", value: "Native 4K @ 120fps" },
      { key: "Ray Tracing", value: "Enhanced RT with AI upscaling" },
    ],
    tags: ["playstation", "ps5", "pro", "console", "4k", "premium", "sony", "ray-tracing"],
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    rating: 4.9,
    reviewCount: 42,
    views: 4100,
  },
  {
    name: "Sony PlayStation 4 Slim",
    categorySlug: "playstation-4",
    brand: "Sony",
    price: 299.99,
    salePrice: 249.99,
    stockQuantity: 40,
    sku: "RG-CON-0004",
    description: "The slimmest, lightest PS4 ever. Experience rich graphics, smooth gameplay, and a massive library of games at an incredible value.",
    shortDescription: "Slim and lightweight PS4 with 1TB storage",
    mainImage: img(IMAGES.consoles, "ps4"),
    galleryImages: [
      { url: img(IMAGES.consoles, "ps4-g1"), alt: "PS4 Slim Front" },
      { url: img(IMAGES.consoles, "ps4-g2"), alt: "PS4 Slim Top" },
    ],
    specifications: [
      { key: "CPU", value: "AMD Jaguar, 8 cores @ 1.6 GHz" },
      { key: "GPU", value: "AMD GCN, 1.84 TFLOPS" },
      { key: "RAM", value: "8 GB GDDR5" },
      { key: "Storage", value: "1 TB HDD" },
    ],
    tags: ["playstation", "ps4", "console", "slim", "sony", "1tb", "value"],
    isBestSeller: true,
    rating: 4.5,
    reviewCount: 156,
    views: 3800,
  },
  {
    name: "Xbox Series X Console",
    categorySlug: "xbox-series-x",
    brand: "Microsoft",
    price: 499.99,
    stockQuantity: 20,
    sku: "RG-CON-0005",
    description: "The fastest, most powerful Xbox ever. Play thousands of games from four generations with 12 teraflops of GPU power, 4K gaming at 120fps, and Quick Resume.",
    shortDescription: "Most powerful Xbox with 12 TFLOPS and 4K@120fps",
    mainImage: img(IMAGES.consoles, "xsx"),
    galleryImages: [
      { url: img(IMAGES.consoles, "xsx-g1"), alt: "Xbox Series X Front" },
      { url: img(IMAGES.consoles, "xsx-g2"), alt: "Xbox Series X Top" },
      { url: img(IMAGES.consoles, "xsx-g3"), alt: "Xbox Series X Back" },
    ],
    specifications: [
      { key: "CPU", value: "AMD Zen 2, 8 cores @ 3.8 GHz" },
      { key: "GPU", value: "AMD RDNA 2, 12 TFLOPS" },
      { key: "RAM", value: "16 GB GDDR6" },
      { key: "Storage", value: "1 TB NVMe SSD" },
      { key: "Resolution", value: "Up to 4K @ 120fps" },
      { key: "Disc Drive", value: "4K UHD Blu-ray" },
    ],
    tags: ["xbox", "series-x", "console", "microsoft", "4k", "gaming", "next-gen", "12tflops"],
    isFeatured: true,
    isTrending: true,
    rating: 4.7,
    reviewCount: 134,
    views: 3900,
    variants: [
      { name: "Standard", sku: "RG-CON-0005-S", price: 499.99, stockQuantity: 12, attributes: [{ key: "Edition", value: "Standard" }, { key: "Color", value: "Black" }] },
      { name: "All-Digital", sku: "RG-CON-0005-AD", price: 399.99, stockQuantity: 8, attributes: [{ key: "Edition", value: "All-Digital" }, { key: "Color", value: "Black" }] },
    ],
  },
  {
    name: "Xbox Series S Console",
    categorySlug: "xbox-series-s",
    brand: "Microsoft",
    price: 299.99,
    salePrice: 259.99,
    stockQuantity: 35,
    sku: "RG-CON-0006",
    description: "The smallest, lightest Xbox ever. Digital-first console delivering 120fps, 4K upscaling, and thousands of games in the most compact form factor.",
    shortDescription: "Compact digital-only Xbox at an incredible price",
    mainImage: img(IMAGES.consoles, "xss"),
    galleryImages: [
      { url: img(IMAGES.consoles, "xss-g1"), alt: "Xbox Series S Front" },
      { url: img(IMAGES.consoles, "xss-g2"), alt: "Xbox Series S Side" },
    ],
    specifications: [
      { key: "CPU", value: "AMD Zen 2, 8 cores @ 3.6 GHz" },
      { key: "GPU", value: "AMD RDNA 2, 4 TFLOPS" },
      { key: "RAM", value: "10 GB GDDR6" },
      { key: "Storage", value: "512 GB NVMe SSD" },
      { key: "Resolution", value: "Up to 1440p @ 120fps" },
    ],
    tags: ["xbox", "series-s", "console", "microsoft", "digital", "compact", "affordable"],
    isBestSeller: true,
    rating: 4.5,
    reviewCount: 112,
    views: 3400,
  },
  {
    name: "Xbox One X Console",
    categorySlug: "xbox-one",
    brand: "Microsoft",
    price: 299.99,
    salePrice: 229.99,
    stockQuantity: 25,
    sku: "RG-CON-0007",
    description: "The world's most powerful console. True 4K gaming, HDR, and a huge library of Xbox One and backward-compatible games.",
    shortDescription: "True 4K gaming console with 6 TFLOPS GPU",
    mainImage: img(IMAGES.consoles, "xboxone"),
    galleryImages: [
      { url: img(IMAGES.consoles, "xboxone-g1"), alt: "Xbox One X Front" },
      { url: img(IMAGES.consoles, "xboxone-g2"), alt: "Xbox One X Back" },
    ],
    specifications: [
      { key: "CPU", value: "AMD Jaguar, 8 cores @ 2.3 GHz" },
      { key: "GPU", value: "AMD GCN, 6 TFLOPS" },
      { key: "RAM", value: "12 GB GDDR5" },
      { key: "Storage", value: "1 TB HDD" },
    ],
    tags: ["xbox", "one-x", "console", "microsoft", "4k", "hdr", "value"],
    rating: 4.3,
    reviewCount: 87,
    views: 2100,
  },
  {
    name: "Nintendo Switch Console",
    categorySlug: "nintendo-switch",
    brand: "Nintendo",
    price: 299.99,
    stockQuantity: 45,
    sku: "RG-CON-0008",
    description: "Play at home on the TV or on the go with this innovative hybrid console. Swap between TV mode, tabletop mode, and handheld mode instantly.",
    shortDescription: "Hybrid console for home and portable gaming",
    mainImage: IMAGES.switch,
    galleryImages: [
      { url: img(IMAGES.switch, "g1"), alt: "Switch Front" },
      { url: img(IMAGES.switch, "g2"), alt: "Switch Dock" },
      { url: img(IMAGES.switch, "g3"), alt: "Switch Handheld" },
    ],
    specifications: [
      { key: "CPU", value: "NVIDIA Tegra X1" },
      { key: "Display", value: "6.2 inch, 720p" },
      { key: "Battery", value: "4.5 - 9 hours" },
      { key: "Storage", value: "32 GB internal" },
      { key: "Resolution", value: "Up to 1080p (TV mode)" },
    ],
    tags: ["nintendo", "switch", "console", "portable", "hybrid", "gaming", "family"],
    isFeatured: true,
    isBestSeller: true,
    rating: 4.6,
    reviewCount: 165,
    views: 4200,
    variants: [
      { name: "Neon Red/Blue", sku: "RG-CON-0008-NR", price: 299.99, stockQuantity: 25, attributes: [{ key: "Color", value: "Neon Red/Blue" }] },
      { name: "Gray", sku: "RG-CON-0008-GY", price: 299.99, stockQuantity: 20, attributes: [{ key: "Color", value: "Gray" }] },
    ],
  },
  {
    name: "Nintendo Switch OLED Model",
    categorySlug: "nintendo-switch-oled",
    brand: "Nintendo",
    price: 349.99,
    stockQuantity: 30,
    sku: "RG-CON-0009",
    description: "The Nintendo Switch OLED Model features a vibrant 7-inch OLED screen, a wide adjustable stand, enhanced audio, and 64GB of internal storage.",
    shortDescription: "Switch with stunning 7-inch OLED display",
    mainImage: img(IMAGES.switch, "oled"),
    galleryImages: [
      { url: img(IMAGES.switch, "oled-g1"), alt: "Switch OLED Front" },
      { url: img(IMAGES.switch, "oled-g2"), alt: "Switch OLED Stand" },
    ],
    specifications: [
      { key: "Display", value: "7 inch OLED, 1280x720" },
      { key: "CPU", value: "NVIDIA Tegra X1" },
      { key: "Storage", value: "64 GB internal" },
      { key: "Audio", value: "Enhanced with improved bass" },
      { key: "Stand", value: "Wide adjustable kickstand" },
    ],
    tags: ["nintendo", "switch", "oled", "console", "portable", "gaming", "display"],
    isNewArrival: true,
    isTrending: true,
    rating: 4.8,
    reviewCount: 78,
    views: 2900,
    variants: [
      { name: "White", sku: "RG-CON-0009-WH", price: 349.99, stockQuantity: 18, attributes: [{ key: "Color", value: "White" }] },
      { name: "Neon Red/Blue", sku: "RG-CON-0009-NR", price: 349.99, stockQuantity: 12, attributes: [{ key: "Color", value: "Neon Red/Blue" }] },
    ],
  },
  {
    name: "Valve Steam Deck",
    categorySlug: "steam-deck",
    brand: "Valve",
    price: 549.99,
    stockQuantity: 12,
    sku: "RG-CON-0010",
    description: "The ultimate portable gaming PC. Play your Steam library anywhere with a custom AMD APU, 7-inch touchscreen, and full PC gaming performance.",
    shortDescription: "Portable PC gaming with Steam library access",
    mainImage: img(IMAGES.consoles, "steamdeck"),
    galleryImages: [
      { url: img(IMAGES.consoles, "sd-g1"), alt: "Steam Deck Front" },
      { url: img(IMAGES.consoles, "sd-g2"), alt: "Steam Deck Back" },
      { url: img(IMAGES.consoles, "sd-g3"), alt: "Steam Deck Screen" },
    ],
    specifications: [
      { key: "APU", value: "Custom AMD, 4 cores @ 3.5 GHz" },
      { key: "GPU", value: "AMD RDNA 2, 1.0-1.6 TFLOPS" },
      { key: "RAM", value: "16 GB LPDDR5" },
      { key: "Storage", value: "512 GB NVMe SSD" },
      { key: "Display", value: "7 inch IPS, 1280x800" },
      { key: "Battery", value: "2-8 hours" },
    ],
    tags: ["steam", "deck", "portable", "pc", "gaming", "valve", "handheld"],
    isTrending: true,
    isNewArrival: true,
    rating: 4.6,
    reviewCount: 67,
    views: 3500,
  },
  // ── Gaming Accessories ──
  {
    name: "DualSense Wireless Controller - Midnight Black",
    categorySlug: "controllers",
    brand: "Sony",
    price: 69.99,
    stockQuantity: 50,
    sku: "RG-ACC-0001",
    description: "Experience a deeper gaming experience with the DualSense controller featuring haptic feedback, adaptive triggers, and a built-in microphone.",
    shortDescription: "PS5 controller with haptic feedback and adaptive triggers",
    mainImage: IMAGES.controllers,
    galleryImages: [
      { url: img(IMAGES.controllers, "g1"), alt: "DualSense Black Front" },
      { url: img(IMAGES.controllers, "g2"), alt: "DualSense Black Back" },
    ],
    specifications: [
      { key: "Connectivity", value: "Bluetooth 5.1, USB-C" },
      { key: "Battery", value: "Up to 12 hours" },
      { key: "Features", value: "Haptic feedback, adaptive triggers" },
      { key: "Weight", value: "280g" },
    ],
    tags: ["controller", "dualsense", "ps5", "sony", "wireless", "haptic", "black"],
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 143,
    views: 3600,
    variants: [
      { name: "Black", sku: "RG-ACC-0001-BK", price: 69.99, stockQuantity: 20, attributes: [{ key: "Color", value: "Black" }], image: IMAGES.controllers },
      { name: "White", sku: "RG-ACC-0001-WH", price: 69.99, stockQuantity: 15, attributes: [{ key: "Color", value: "White" }], image: img(IMAGES.controllers, "w") },
      { name: "Blue", sku: "RG-ACC-0001-BL", price: 69.99, stockQuantity: 10, attributes: [{ key: "Color", value: "Blue" }] },
      { name: "Red", sku: "RG-ACC-0001-RD", price: 69.99, stockQuantity: 5, attributes: [{ key: "Color", value: "Red" }] },
    ],
  },
  {
    name: "Xbox Wireless Controller - Carbon Black",
    categorySlug: "controllers",
    brand: "Microsoft",
    price: 59.99,
    stockQuantity: 45,
    sku: "RG-ACC-0002",
    description: "Designed for comfort with textured grip, the Xbox Wireless Controller features a Share button for easy screenshot and recording.",
    shortDescription: "Ergonomic Xbox controller with Share button",
    mainImage: img(IMAGES.controllers, "xbox"),
    galleryImages: [
      { url: img(IMAGES.controllers, "xbox-g1"), alt: "Xbox Controller Front" },
      { url: img(IMAGES.controllers, "xbox-g2"), alt: "Xbox Controller Back" },
    ],
    specifications: [
      { key: "Connectivity", value: "Bluetooth, Xbox Wireless, USB-C" },
      { key: "Battery", value: "Up to 40 hours (AA)" },
      { key: "Platform", value: "Xbox Series X|S, Xbox One, PC" },
      { key: "Weight", value: "287g" },
    ],
    tags: ["controller", "xbox", "microsoft", "wireless", "ergonomic", "black"],
    isBestSeller: true,
    rating: 4.6,
    reviewCount: 128,
    views: 3200,
    variants: [
      { name: "Black", sku: "RG-ACC-0002-BK", price: 59.99, stockQuantity: 20, attributes: [{ key: "Color", value: "Black" }] },
      { name: "White", sku: "RG-ACC-0002-WH", price: 59.99, stockQuantity: 15, attributes: [{ key: "Color", value: "White" }] },
      { name: "Blue", sku: "RG-ACC-0002-BL", price: 59.99, stockQuantity: 10, attributes: [{ key: "Color", value: "Blue" }] },
      { name: "Red", sku: "RG-ACC-0002-RD", price: 59.99, stockQuantity: 0, attributes: [{ key: "Color", value: "Red" }] },
    ],
  },
  {
    name: "SteelSeries Arctis Nova Pro Wireless",
    categorySlug: "headsets",
    brand: "SteelSeries",
    price: 179.99,
    salePrice: 149.99,
    stockQuantity: 20,
    sku: "RG-ACC-0003",
    description: "Premium wireless gaming headset with Active Noise Cancellation, Hi-Res audio, multi-system connectivity, and a hot-swappable battery system.",
    shortDescription: "Premium ANC headset with Hi-Res audio",
    mainImage: IMAGES.headsets,
    galleryImages: [
      { url: img(IMAGES.headsets, "g1"), alt: "Arctis Nova Pro Front" },
      { url: img(IMAGES.headsets, "g2"), alt: "Arctis Nova Pro Side" },
      { url: img(IMAGES.headsets, "g3"), alt: "Arctis Nova Pro Ear Cup" },
    ],
    specifications: [
      { key: "Driver Size", value: "40mm" },
      { key: "Frequency Response", value: "10Hz - 40kHz" },
      { key: "Battery", value: "Up to 22 hours (ANC on)" },
      { key: "Connectivity", value: "2.4GHz, Bluetooth 5.0" },
      { key: "ANC", value: "4-mic hybrid active noise cancellation" },
    ],
    tags: ["headset", "wireless", "anc", "steelseries", "premium", "hi-res", "gaming"],
    isFeatured: true,
    rating: 4.8,
    reviewCount: 76,
    views: 2800,
    variants: [
      { name: "Black", sku: "RG-ACC-0003-BK", price: 179.99, salePrice: 149.99, stockQuantity: 12, attributes: [{ key: "Color", value: "Black" }] },
      { name: "White", sku: "RG-ACC-0003-WH", price: 179.99, salePrice: 149.99, stockQuantity: 8, attributes: [{ key: "Color", value: "White" }] },
    ],
  },
  {
    name: "Razer BlackShark V2 Pro",
    categorySlug: "headsets",
    brand: "Razer",
    price: 129.99,
    stockQuantity: 25,
    sku: "RG-ACC-0004",
    description: "Award-winning esports headset with TriForce Titanium 50mm drivers, HyperClear Super Wideband Mic, and THX Spatial Audio.",
    shortDescription: "Esports headset with THX Spatial Audio",
    mainImage: img(IMAGES.headsets, "razer"),
    galleryImages: [
      { url: img(IMAGES.headsets, "razer-g1"), alt: "BlackShark V2 Pro Front" },
      { url: img(IMAGES.headsets, "razer-g2"), alt: "BlackShark V2 Pro Side" },
    ],
    specifications: [
      { key: "Driver Size", value: "50mm TriForce Titanium" },
      { key: "Frequency Response", value: "12Hz - 28kHz" },
      { key: "Battery", value: "Up to 70 hours" },
      { key: "Microphone", value: "HyperClear Super Wideband" },
    ],
    tags: ["headset", "razer", "wireless", "esports", "thx", "gaming", "titanium"],
    isTrending: true,
    rating: 4.6,
    reviewCount: 92,
    views: 2400,
  },
  {
    name: "PlayStation DualSense Charging Station",
    categorySlug: "charging-stations",
    brand: "Sony",
    price: 29.99,
    stockQuantity: 35,
    sku: "RG-ACC-0005",
    description: "Charge up to two DualSense wireless controllers simultaneously with the click-in design. Fully charges controllers in approximately 3 hours.",
    shortDescription: "Charge 2 DualSense controllers simultaneously",
    mainImage: img(IMAGES.controllers, "charge"),
    galleryImages: [
      { url: img(IMAGES.controllers, "charge-g1"), alt: "Charging Station Front" },
      { url: img(IMAGES.controllers, "charge-g2"), alt: "Charging Station with Controllers" },
    ],
    specifications: [
      { key: "Capacity", value: "2 controllers" },
      { key: "Charge Time", value: "~3 hours" },
      { key: "Connection", value: "Click-in connector" },
      { key: "Power", value: "USB-C" },
    ],
    tags: ["charging", "station", "dualsense", "ps5", "sony", "accessory"],
    rating: 4.4,
    reviewCount: 68,
    views: 1800,
  },
  {
    name: "Razer DeathAdder V3 Pro Gaming Mouse",
    categorySlug: "gaming-mouse",
    brand: "Razer",
    price: 89.99,
    salePrice: 69.99,
    stockQuantity: 30,
    sku: "RG-ACC-0006",
    description: "Ultra-lightweight wireless gaming mouse with Focus Pro 30K optical sensor, 90-hour battery life, and ergonomic design trusted by esports pros.",
    shortDescription: "Ultra-lightweight wireless mouse with 30K sensor",
    mainImage: IMAGES.mouse,
    galleryImages: [
      { url: img(IMAGES.mouse, "g1"), alt: "DeathAdder V3 Pro Top" },
      { url: img(IMAGES.mouse, "g2"), alt: "DeathAdder V3 Pro Side" },
    ],
    specifications: [
      { key: "Sensor", value: "Focus Pro 30K Optical" },
      { key: "DPI", value: "Up to 30,000" },
      { key: "Weight", value: "63g" },
      { key: "Battery", value: "Up to 90 hours" },
      { key: "Switches", value: "Gen-3 Optical" },
    ],
    tags: ["mouse", "razer", "wireless", "lightweight", "esports", "gaming", "30k"],
    isFeatured: true,
    rating: 4.7,
    reviewCount: 89,
    views: 2600,
  },
  {
    name: "Logitech G Pro X Superlight 2",
    categorySlug: "gaming-mouse",
    brand: "Logitech",
    price: 159.99,
    stockQuantity: 22,
    sku: "RG-ACC-0007",
    description: "Professional-grade wireless gaming mouse weighing just 60g. Features HERO 2 sensor with 32,000 DPI and LIGHTSPEED wireless technology.",
    shortDescription: "Pro wireless mouse with HERO 2 sensor at 60g",
    mainImage: img(IMAGES.mouse, "logi"),
    galleryImages: [
      { url: img(IMAGES.mouse, "logi-g1"), alt: "G Pro X Superlight 2 Top" },
      { url: img(IMAGES.mouse, "logi-g2"), alt: "G Pro X Superlight 2 Side" },
    ],
    specifications: [
      { key: "Sensor", value: "HERO 2" },
      { key: "DPI", value: "Up to 32,000" },
      { key: "Weight", value: "60g" },
      { key: "Battery", value: "Up to 95 hours" },
      { key: "Connectivity", value: "LIGHTSPEED, Bluetooth" },
    ],
    tags: ["mouse", "logitech", "wireless", "pro", "lightweight", "gaming", "hero-2"],
    isTrending: true,
    rating: 4.8,
    reviewCount: 54,
    views: 2100,
  },
  {
    name: "Razer Huntsman V3 Pro Analog",
    categorySlug: "gaming-keyboards",
    brand: "Razer",
    price: 199.99,
    stockQuantity: 18,
    sku: "RG-ACC-0008",
    description: "Full-size analog gaming keyboard with Razer Analog Optical switches, adjustable actuation, and per-key RGB lighting with Chroma RGB.",
    shortDescription: "Analog optical keyboard with adjustable actuation",
    mainImage: IMAGES.keyboards,
    galleryImages: [
      { url: img(IMAGES.keyboards, "g1"), alt: "Huntsman V3 Pro Top" },
      { url: img(IMAGES.keyboards, "g2"), alt: "Huntsman V3 Pro Angled" },
    ],
    specifications: [
      { key: "Switches", value: "Razer Analog Optical" },
      { key: "Actuation", value: "0.1mm - 4.0mm adjustable" },
      { key: "Keycaps", value: "PBT Doubleshot" },
      { key: "Lighting", value: "Per-key RGB Chroma" },
      { key: "Connection", value: "USB-C detachable" },
    ],
    tags: ["keyboard", "razer", "analog", "optical", "rgb", "gaming", "mechanical"],
    isNewArrival: true,
    rating: 4.6,
    reviewCount: 38,
    views: 1900,
  },
  {
    name: "Corsair K100 RGB Mechanical Keyboard",
    categorySlug: "gaming-keyboards",
    brand: "Corsair",
    price: 229.99,
    salePrice: 199.99,
    stockQuantity: 15,
    sku: "RG-ACC-0009",
    description: "Premium mechanical gaming keyboard with OPX optical-macro switches, iCUE control wheel, and 44-zone RGB LightEdge.",
    shortDescription: "Premium mechanical keyboard with iCUE control wheel",
    mainImage: img(IMAGES.keyboards, "corsair"),
    galleryImages: [
      { url: img(IMAGES.keyboards, "corsair-g1"), alt: "K100 RGB Top" },
      { url: img(IMAGES.keyboards, "corsair-g2"), alt: "K100 RGB Side" },
    ],
    specifications: [
      { key: "Switches", value: "Corsair OPX optical-macro" },
      { key: "Polling Rate", value: "4,000 Hz" },
      { key: "Keycaps", value: "PBT Doubleshot" },
      { key: "Lighting", value: "44-zone RGB LightEdge" },
      { key: "Features", value: "iCUE control wheel, macro keys" },
    ],
    tags: ["keyboard", "corsair", "mechanical", "rgb", "optical", "gaming", "premium"],
    rating: 4.5,
    reviewCount: 67,
    views: 1700,
  },
  {
    name: "Corsair MM700 RGB Gaming Mouse Pad",
    categorySlug: "gaming-mouse-pads",
    brand: "Corsair",
    price: 49.99,
    stockQuantity: 40,
    sku: "RG-ACC-0010",
    description: "Extended RGB gaming mouse pad with 3-zone dynamic RGB lighting, micro-texture woven surface, and USB passthrough.",
    shortDescription: "Extended RGB mouse pad with 3-zone lighting",
    mainImage: img(IMAGES.mouse, "pad"),
    galleryImages: [
      { url: img(IMAGES.mouse, "pad-g1"), alt: "MM700 Top" },
      { url: img(IMAGES.mouse, "pad-g2"), alt: "MM700 RGB" },
    ],
    specifications: [
      { key: "Size", value: "930mm x 400mm x 4mm" },
      { key: "Surface", value: "Micro-texture woven" },
      { key: "RGB", value: "3-zone dynamic lighting" },
      { key: "Connection", value: "USB-C" },
    ],
    tags: ["mouse-pad", "corsair", "rgb", "extended", "gaming", "surface"],
    rating: 4.3,
    reviewCount: 45,
    views: 1200,
  },
  {
    name: "Secretlab TITAN Evo 2024",
    categorySlug: "gaming-chairs",
    brand: "Secretlab",
    price: 499.99,
    salePrice: 449.99,
    stockQuantity: 10,
    sku: "RG-ACC-0011",
    description: "Award-winning ergonomic gaming chair with 4-way lumbar support, magnetic headrest, and premium NEO Hybrid Leatherette or SoftWeave Plus fabric.",
    shortDescription: "Ergonomic chair with 4-way lumbar support",
    mainImage: IMAGES.chairs,
    galleryImages: [
      { url: img(IMAGES.chairs, "g1"), alt: "TITAN Evo Front" },
      { url: img(IMAGES.chairs, "g2"), alt: "TITAN Evo Side" },
      { url: img(IMAGES.chairs, "g3"), alt: "TITAN Evo Detail" },
    ],
    specifications: [
      { key: "Material", value: "NEO Hybrid Leatherette" },
      { key: "Lumbar", value: "4-way L-ADAPT" },
      { key: "Weight Capacity", value: "Up to 130 kg" },
      { key: "Recline", value: "85 - 165 degrees" },
      { key: "Armrests", value: "4D Armrests" },
    ],
    tags: ["chair", "secretlab", "ergonomic", "premium", "gaming", "leather", "titan"],
    isFeatured: true,
    rating: 4.8,
    reviewCount: 112,
    views: 2900,
  },
  {
    name: "Elgato HD60 X Capture Card",
    categorySlug: "capture-cards",
    brand: "Elgato",
    price: 159.99,
    stockQuantity: 18,
    sku: "RG-ACC-0012",
    description: "Capture gameplay in 4K60 HDR10 or 1080p60 with zero-lag passthrough. VRR support for PS5, Xbox Series X, and PC gaming.",
    shortDescription: "4K60 HDR10 capture card with VRR passthrough",
    mainImage: img(IMAGES.consoles, "capture"),
    galleryImages: [
      { url: img(IMAGES.consoles, "capture-g1"), alt: "HD60 X Front" },
      { url: img(IMAGES.consoles, "capture-g2"), alt: "HD60 X Ports" },
    ],
    specifications: [
      { key: "Max Resolution", value: "4K60 HDR10" },
      { key: "Passthrough", value: "4K60, 1440p120, 1080p60 VRR" },
      { key: "Input", value: "HDMI 2.0" },
      { key: "Output", value: "HDMI 2.0 + USB 3.0" },
      { key: "VRR", value: "Yes (PS5, Xbox, PC)" },
    ],
    tags: ["capture", "elgato", "4k", "streaming", "hdr", "vrr", "recording"],
    isTrending: true,
    rating: 4.7,
    reviewCount: 56,
    views: 1800,
  },
  {
    name: "Cable Management Kit - 120 Pieces",
    categorySlug: "cable-management",
    brand: "RetroGaming",
    price: 19.99,
    stockQuantity: 60,
    sku: "RG-ACC-0013",
    description: "Complete cable management solution with reusable velcro ties, cable clips, cable sleeves, and a cable organizer box for a clean gaming setup.",
    shortDescription: "120-piece kit for a clean gaming setup",
    mainImage: img(IMAGES.consoles, "cables"),
    galleryImages: [
      { url: img(IMAGES.consoles, "cables-g1"), alt: "Cable Kit Contents" },
      { url: img(IMAGES.consoles, "cables-g2"), alt: "Cable Kit Applied" },
    ],
    specifications: [
      { key: "Pieces", value: "120" },
      { key: "Types", value: "Velcro ties, clips, sleeves, organizer box" },
      { key: "Reusable", value: "Yes" },
      { key: "Max Bundle Size", value: "1 inch diameter" },
    ],
    tags: ["cable", "management", "organizer", "velcro", "setup", "clean"],
    rating: 4.2,
    reviewCount: 34,
    views: 800,
  },
  {
    name: "PlayStation 5 Console Cover - Midnight Black",
    categorySlug: "skin-covers",
    brand: "Sony",
    price: 54.99,
    stockQuantity: 22,
    sku: "RG-ACC-0014",
    description: "Replaceable PS5 console covers in Midnight Black. Easy snap-on design to customize your PS5 without voiding warranty.",
    shortDescription: "Official PS5 replacement cover in black",
    mainImage: img(IMAGES.consoles, "cover"),
    galleryImages: [
      { url: img(IMAGES.consoles, "cover-g1"), alt: "PS5 Cover Black" },
      { url: img(IMAGES.consoles, "cover-g2"), alt: "PS5 Cover Installed" },
    ],
    specifications: [
      { key: "Compatibility", value: "PS5 Disc & Digital" },
      { key: "Material", value: "ABS Plastic" },
      { key: "Installation", value: "Snap-on, tool-free" },
      { key: "Color", value: "Midnight Black" },
    ],
    tags: ["cover", "ps5", "sony", "black", "customization", "console"],
    rating: 4.5,
    reviewCount: 47,
    views: 1400,
  },
  // ── PS5 Games ──
  {
    name: "Marvel's Spider-Man 2",
    categorySlug: "ps5-games",
    brand: "Sony Interactive Entertainment",
    price: 69.99,
    stockQuantity: 40,
    sku: "RG-PS5-0001",
    description: "Spider-Men Peter Parker and Miles Morales face the ultimate test of strength inside and outside the mask as they work together to save Marvel's New York.",
    shortDescription: "Swing through Marvel's New York as both Spider-Men",
    mainImage: IMAGES.games,
    galleryImages: [
      { url: img(IMAGES.games, "spider2-g1"), alt: "Spider-Man 2 Cover" },
      { url: img(IMAGES.games, "spider2-g2"), alt: "Spider-Man 2 Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "PS5" },
      { key: "Genre", value: "Action-Adventure" },
      { key: "Players", value: "1" },
      { key: "Storage", value: "98 GB" },
    ],
    tags: ["ps5", "spider-man", "action", "adventure", "marvel", "exclusive", "open-world"],
    isFeatured: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 187,
    views: 5000,
  },
  {
    name: "God of War Ragnarok",
    categorySlug: "ps5-games",
    brand: "Sony Interactive Entertainment",
    price: 59.99,
    stockQuantity: 35,
    sku: "RG-PS5-0002",
    description: "Embark on an epic and heartfelt journey as Kratos and Atreus struggle with holding on and letting go. Witness the changing dynamic of their relationship.",
    shortDescription: "The epic Norse adventure continues with Kratos and Atreus",
    mainImage: img(IMAGES.games, "gow"),
    galleryImages: [
      { url: img(IMAGES.games, "gow-g1"), alt: "God of War Ragnarok Cover" },
      { url: img(IMAGES.games, "gow-g2"), alt: "God of War Ragnarok Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "PS5" },
      { key: "Genre", value: "Action-Adventure" },
      { key: "Players", value: "1" },
      { key: "Storage", value: "118 GB" },
    ],
    tags: ["ps5", "god-of-war", "action", "adventure", "norse", "exclusive", "kratos"],
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 165,
    views: 4200,
  },
  {
    name: "Final Fantasy XVI",
    categorySlug: "ps5-games",
    brand: "Square Enix",
    price: 59.99,
    salePrice: 49.99,
    stockQuantity: 30,
    sku: "RG-PS5-0003",
    description: "An epic dark fantasy experience from the creators of Final Fantasy XV. Engage in visceral real-time combat as Clive Rosfield in the world of Valisthea.",
    shortDescription: "Dark fantasy action RPG set in the world of Valisthea",
    mainImage: img(IMAGES.games, "ff16"),
    galleryImages: [
      { url: img(IMAGES.games, "ff16-g1"), alt: "FF XVI Cover" },
      { url: img(IMAGES.games, "ff16-g2"), alt: "FF XVI Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "PS5" },
      { key: "Genre", value: "Action RPG" },
      { key: "Players", value: "1" },
      { key: "Storage", value: "90 GB" },
    ],
    tags: ["ps5", "final-fantasy", "rpg", "action", "square-enix", "fantasy", "exclusive"],
    rating: 4.6,
    reviewCount: 98,
    views: 3100,
  },
  {
    name: "Gran Turismo 7",
    categorySlug: "ps5-games",
    brand: "Sony Interactive Entertainment",
    price: 59.99,
    stockQuantity: 28,
    sku: "RG-PS5-0004",
    description: "The best of Gran Turismo. Experience the complete real racing simulator with stunning graphics, over 400 cars, and iconic tracks.",
    shortDescription: "The complete real racing simulator with 400+ cars",
    mainImage: img(IMAGES.games, "gt7"),
    galleryImages: [
      { url: img(IMAGES.games, "gt7-g1"), alt: "GT7 Cover" },
      { url: img(IMAGES.games, "gt7-g2"), alt: "GT7 Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "PS5" },
      { key: "Genre", value: "Racing" },
      { key: "Players", value: "1-2" },
      { key: "Cars", value: "400+" },
    ],
    tags: ["ps5", "gran-turismo", "racing", "simulator", "exclusive", "cars", "motorsport"],
    rating: 4.5,
    reviewCount: 76,
    views: 2400,
  },
  {
    name: "Horizon Forbidden West",
    categorySlug: "ps5-games",
    brand: "Sony Interactive Entertainment",
    price: 49.99,
    stockQuantity: 32,
    sku: "RG-PS5-0005",
    description: "Join Aloy as she braves the Forbidden West - a majestic but dangerous frontier that conceals mysterious threats.",
    shortDescription: "Explore the Forbidden West in this epic open-world RPG",
    mainImage: img(IMAGES.games, "horizon"),
    galleryImages: [
      { url: img(IMAGES.games, "horizon-g1"), alt: "Horizon FW Cover" },
      { url: img(IMAGES.games, "horizon-g2"), alt: "Horizon FW Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "PS5" },
      { key: "Genre", value: "Action RPG" },
      { key: "Players", value: "1" },
      { key: "Storage", value: "98 GB" },
    ],
    tags: ["ps5", "horizon", "open-world", "rpg", "action", "exclusive", "adventure"],
    isTrending: true,
    rating: 4.7,
    reviewCount: 112,
    views: 3400,
  },
  {
    name: "The Last of Us Part I",
    categorySlug: "ps5-games",
    brand: "Sony Interactive Entertainment",
    price: 69.99,
    stockQuantity: 25,
    sku: "RG-PS5-0006",
    description: "A complete remake of the original game rebuilt for PS5. Experience the emotional post-apocalyptic journey of Joel and Ellie like never before.",
    shortDescription: "Complete remake of the award-winning post-apocalyptic adventure",
    mainImage: img(IMAGES.games, "tlou"),
    galleryImages: [
      { url: img(IMAGES.games, "tlou-g1"), alt: "TLOU Part I Cover" },
      { url: img(IMAGES.games, "tlou-g2"), alt: "TLOU Part I Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "PS5" },
      { key: "Genre", value: "Action-Adventure" },
      { key: "Players", value: "1" },
      { key: "Storage", value: "80 GB" },
    ],
    tags: ["ps5", "last-of-us", "action", "adventure", "remake", "exclusive", "story"],
    rating: 4.8,
    reviewCount: 134,
    views: 3800,
  },
  {
    name: "Uncharted: Legacy of Thieves Collection",
    categorySlug: "ps5-games",
    brand: "Sony Interactive Entertainment",
    price: 49.99,
    stockQuantity: 22,
    sku: "RG-PS5-0007",
    description: "Two blockbuster adventures remastered for PS5. Play as Nathan Drake and Chloe Frazer in their greatest adventures.",
    shortDescription: "Two legendary adventures remastered for PS5",
    mainImage: img(IMAGES.games, "uncharted"),
    galleryImages: [
      { url: img(IMAGES.games, "uncharted-g1"), alt: "Uncharted Cover" },
      { url: img(IMAGES.games, "uncharted-g2"), alt: "Uncharted Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "PS5" },
      { key: "Genre", value: "Action-Adventure" },
      { key: "Players", value: "1" },
      { key: "Includes", value: "Uncharted 4, Lost Legacy" },
    ],
    tags: ["ps5", "uncharted", "action", "adventure", "collection", "exclusive", "naughty-dog"],
    rating: 4.7,
    reviewCount: 89,
    views: 2600,
  },
  {
    name: "Ratchet & Clank: Rift Apart",
    categorySlug: "ps5-games",
    brand: "Sony Interactive Entertainment",
    price: 39.99,
    stockQuantity: 28,
    sku: "RG-PS5-0008",
    description: "Blast your way through an interdimensional adventure with Ratchet and Clank. Harness the power of the PS5 with near-instant load times.",
    shortDescription: "Interdimensional adventure taking full advantage of PS5",
    mainImage: img(IMAGES.games, "ratchet"),
    galleryImages: [
      { url: img(IMAGES.games, "ratchet-g1"), alt: "Rift Apart Cover" },
      { url: img(IMAGES.games, "ratchet-g2"), alt: "Rift Apart Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "PS5" },
      { key: "Genre", value: "Platformer" },
      { key: "Players", value: "1" },
      { key: "Storage", value: "40 GB" },
    ],
    tags: ["ps5", "ratchet-clank", "platformer", "exclusive", "family", "action"],
    rating: 4.7,
    reviewCount: 78,
    views: 2200,
  },
  // ── PS4 Games ──
  {
    name: "Resident Evil Village",
    categorySlug: "ps4-games",
    brand: "Capcom",
    price: 39.99,
    salePrice: 29.99,
    stockQuantity: 35,
    sku: "RG-PS4-0001",
    description: "Survive the horrors of a mysterious village as Ethan Winters. Experience the next chapter of this acclaimed survival horror series.",
    shortDescription: "Survival horror in a mysterious European village",
    mainImage: img(IMAGES.games, "revillage"),
    galleryImages: [
      { url: img(IMAGES.games, "revillage-g1"), alt: "RE Village Cover" },
      { url: img(IMAGES.games, "revillage-g2"), alt: "RE Village Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "PS4, PS5" },
      { key: "Genre", value: "Survival Horror" },
      { key: "Players", value: "1" },
      { key: "Storage", value: "35 GB" },
    ],
    tags: ["ps4", "resident-evil", "horror", "survival", "capcom", "action"],
    rating: 4.6,
    reviewCount: 102,
    views: 2800,
  },
  {
    name: "Ghost of Tsushima Director's Cut",
    categorySlug: "ps4-games",
    brand: "Sony Interactive Entertainment",
    price: 39.99,
    stockQuantity: 30,
    sku: "RG-PS4-0002",
    description: "The complete Ghost of Tsushima experience with Iki Island expansion. Forge your path as Jin Sakai in this open-world samurai epic.",
    shortDescription: "Samurai epic with Iki Island expansion",
    mainImage: img(IMAGES.games, "tsushima"),
    galleryImages: [
      { url: img(IMAGES.games, "tsushima-g1"), alt: "Tsushima Cover" },
      { url: img(IMAGES.games, "tsushima-g2"), alt: "Tsushima Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "PS4, PS5" },
      { key: "Genre", value: "Action-Adventure" },
      { key: "Players", value: "1" },
      { key: "Includes", value: "Iki Island expansion" },
    ],
    tags: ["ps4", "ghost-of-tsushima", "open-world", "samurai", "action", "exclusive", "japan"],
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 156,
    views: 3600,
  },
  {
    name: "Bloodborne",
    categorySlug: "ps4-games",
    brand: "Sony Interactive Entertainment",
    price: 29.99,
    stockQuantity: 20,
    sku: "RG-PS4-0003",
    description: "Hunt your nightmares in the gothic city of Yharnam. A challenging action RPG from the creators of Dark Souls.",
    shortDescription: "Gothic action RPG from the creators of Dark Souls",
    mainImage: img(IMAGES.games, "bloodborne"),
    galleryImages: [
      { url: img(IMAGES.games, "bloodborne-g1"), alt: "Bloodborne Cover" },
      { url: img(IMAGES.games, "bloodborne-g2"), alt: "Bloodborne Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "PS4" },
      { key: "Genre", value: "Action RPG" },
      { key: "Players", value: "1-3" },
      { key: "Storage", value: "25 GB" },
    ],
    tags: ["ps4", "bloodborne", "rpg", "action", "from-software", "exclusive", "gothic"],
    rating: 4.9,
    reviewCount: 178,
    views: 4500,
  },
  {
    name: "Persona 5 Royal",
    categorySlug: "ps4-games",
    brand: "Atlus",
    price: 39.99,
    stockQuantity: 25,
    sku: "RG-PS4-0004",
    description: "The definitive version of the award-winning RPG. Lead a group of Phantom Thieves in stylish turn-based combat against the corrupt forces of society.",
    shortDescription: "Definitive JRPG with style and substance",
    mainImage: img(IMAGES.games, "persona5"),
    galleryImages: [
      { url: img(IMAGES.games, "persona5-g1"), alt: "Persona 5 Royal Cover" },
      { url: img(IMAGES.games, "persona5-g2"), alt: "Persona 5 Royal Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "PS4" },
      { key: "Genre", value: "JRPG" },
      { key: "Players", value: "1" },
      { key: "Hours", value: "100+" },
    ],
    tags: ["ps4", "persona", "jrpg", "atlus", "turn-based", "style", "anime"],
    rating: 4.9,
    reviewCount: 134,
    views: 3200,
  },
  // ── PS3/PS2/PS Vita Games ──
  {
    name: "God of War III Remastered",
    categorySlug: "ps3-games",
    brand: "Sony Interactive Entertainment",
    price: 19.99,
    stockQuantity: 15,
    sku: "RG-PS3-0001",
    description: "Experience Kratos' epic battle against the gods of Olympus in this remastered PS3 classic with enhanced graphics.",
    shortDescription: "Remastered epic battle against the gods",
    mainImage: img(IMAGES.games, "gow3"),
    galleryImages: [
      { url: img(IMAGES.games, "gow3-g1"), alt: "God of War III Cover" },
    ],
    specifications: [
      { key: "Platform", value: "PS3, PS4" },
      { key: "Genre", value: "Action-Adventure" },
      { key: "Players", value: "1" },
    ],
    tags: ["ps3", "god-of-war", "action", "adventure", "kratos", "remastered"],
    rating: 4.6,
    reviewCount: 112,
    views: 2100,
  },
  {
    name: "Metal Gear Solid V: The Phantom Pain",
    categorySlug: "ps3-games",
    brand: "Konami",
    price: 14.99,
    stockQuantity: 12,
    sku: "RG-PS3-0002",
    description: "The legendary tactical espionage action series reaches its conclusion in this open-world masterpiece.",
    shortDescription: "Open-world tactical espionage action masterpiece",
    mainImage: img(IMAGES.games, "mgs5"),
    galleryImages: [
      { url: img(IMAGES.games, "mgs5-g1"), alt: "MGS V Cover" },
    ],
    specifications: [
      { key: "Platform", value: "PS3, PS4, Xbox" },
      { key: "Genre", value: "Stealth Action" },
      { key: "Players", value: "1" },
    ],
    tags: ["ps3", "metal-gear", "stealth", "action", "konami", "open-world"],
    rating: 4.7,
    reviewCount: 145,
    views: 2800,
  },
  {
    name: "Persona 4 Golden",
    categorySlug: "ps-vita-games",
    brand: "Atlus",
    price: 29.99,
    stockQuantity: 10,
    sku: "RG-VIT-0001",
    description: "The definitive version of the beloved JRPG. Explore the Midnight World and uncover the truth behind the serial murders in Inaba.",
    shortDescription: "Beloved JRPG remastered for PS Vita",
    mainImage: img(IMAGES.games, "p4g"),
    galleryImages: [
      { url: img(IMAGES.games, "p4g-g1"), alt: "P4G Cover" },
    ],
    specifications: [
      { key: "Platform", value: "PS Vita, PC" },
      { key: "Genre", value: "JRPG" },
      { key: "Players", value: "1" },
      { key: "Hours", value: "80+" },
    ],
    tags: ["vita", "persona", "jrpg", "atlus", "rpg", "handheld"],
    rating: 4.9,
    reviewCount: 89,
    views: 1500,
  },
  {
    name: "Uncharted: Golden Abyss",
    categorySlug: "ps-vita-games",
    brand: "Sony Interactive Entertainment",
    price: 19.99,
    stockQuantity: 8,
    sku: "RG-VIT-0002",
    description: "Join Nathan Drake on a thrilling adventure through the jungles of Central America in this PS Vita exclusive.",
    shortDescription: "PS Vita exclusive Uncharted adventure",
    mainImage: img(IMAGES.games, "uncharted-vita"),
    galleryImages: [
      { url: img(IMAGES.games, "uncharted-vita-g1"), alt: "Golden Abyss Cover" },
    ],
    specifications: [
      { key: "Platform", value: "PS Vita" },
      { key: "Genre", value: "Action-Adventure" },
      { key: "Players", value: "1" },
    ],
    tags: ["vita", "uncharted", "action", "adventure", "exclusive", "handheld"],
    rating: 4.5,
    reviewCount: 67,
    views: 1100,
  },
  {
    name: "Hollow Knight",
    categorySlug: "playstation-indies",
    brand: "Team Cherry",
    price: 14.99,
    stockQuantity: 30,
    sku: "RG-IND-0001",
    description: "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes.",
    shortDescription: "Epic action adventure in a ruined insect kingdom",
    mainImage: img(IMAGES.games, "hollowknight"),
    galleryImages: [
      { url: img(IMAGES.games, "hk-g1"), alt: "Hollow Knight Cover" },
    ],
    specifications: [
      { key: "Platform", value: "PS4, PS5, Switch, PC" },
      { key: "Genre", value: "Metroidvania" },
      { key: "Players", value: "1" },
    ],
    tags: ["indie", "metroidvania", "action", "adventure", "atmospheric", "hand-drawn"],
    rating: 4.8,
    reviewCount: 167,
    views: 3200,
  },
  {
    name: "Celeste",
    categorySlug: "playstation-indies",
    brand: "Maddy Makes Games",
    price: 19.99,
    stockQuantity: 25,
    sku: "RG-IND-0002",
    description: "Help Madeline survive her inner demons on her journey to the top of Celeste Mountain in this super-tight platformer.",
    shortDescription: "Tight platformer about overcoming inner demons",
    mainImage: img(IMAGES.games, "celeste"),
    galleryImages: [
      { url: img(IMAGES.games, "celeste-g1"), alt: "Celeste Cover" },
    ],
    specifications: [
      { key: "Platform", value: "PS4, Switch, PC" },
      { key: "Genre", value: "Platformer" },
      { key: "Players", value: "1" },
    ],
    tags: ["indie", "platformer", "narrative", "challenging", "pixel-art", "story"],
    rating: 4.8,
    reviewCount: 134,
    views: 2400,
  },
  {
    name: "Returnal",
    categorySlug: "playstation-exclusives",
    brand: "Sony Interactive Entertainment",
    price: 59.99,
    salePrice: 39.99,
    stockQuantity: 18,
    sku: "RG-PSX-0001",
    description: "Break the cycle of chaos on an always-changing alien planet in this third-person roguelike shooter from Housemarque.",
    shortDescription: "Alien planet roguelike shooter from Housemarque",
    mainImage: img(IMAGES.games, "returnal"),
    galleryImages: [
      { url: img(IMAGES.games, "returnal-g1"), alt: "Returnal Cover" },
      { url: img(IMAGES.games, "returnal-g2"), alt: "Returnal Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "PS5" },
      { key: "Genre", value: "Roguelike Shooter" },
      { key: "Players", value: "1" },
    ],
    tags: ["ps5", "returnal", "roguelike", "shooter", "exclusive", "alien", "housemarque"],
    rating: 4.6,
    reviewCount: 78,
    views: 2100,
  },
  // ── Xbox Games ──
  {
    name: "Halo Infinite",
    categorySlug: "xbox-series-xs-games",
    brand: "Microsoft",
    price: 59.99,
    stockQuantity: 30,
    sku: "RG-XBX-0001",
    description: "The Master Chief returns in Halo Infinite, the most expansive and adventurous campaign yet. Join the fight and become the hero.",
    shortDescription: "Master Chief returns in the most expansive Halo yet",
    mainImage: img(IMAGES.games, "halo"),
    galleryImages: [
      { url: img(IMAGES.games, "halo-g1"), alt: "Halo Infinite Cover" },
      { url: img(IMAGES.games, "halo-g2"), alt: "Halo Infinite Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "Xbox Series X|S, PC" },
      { key: "Genre", value: "FPS" },
      { key: "Players", value: "1-4" },
      { key: "Storage", value: "50 GB" },
    ],
    tags: ["xbox", "halo", "fps", "shooter", "multiplayer", "exclusive", "master-chief"],
    isFeatured: true,
    rating: 4.5,
    reviewCount: 156,
    views: 4200,
  },
  {
    name: "Forza Horizon 5",
    categorySlug: "xbox-series-xs-games",
    brand: "Microsoft",
    price: 59.99,
    stockQuantity: 35,
    sku: "RG-XBX-0002",
    description: "Your Ultimate Horizon Adventure awaits! Explore the vibrant landscapes of Mexico with limitless, fun driving actions.",
    shortDescription: "Open-world racing adventure set in Mexico",
    mainImage: img(IMAGES.games, "forza"),
    galleryImages: [
      { url: img(IMAGES.games, "forza-g1"), alt: "Forza Horizon 5 Cover" },
      { url: img(IMAGES.games, "forza-g2"), alt: "Forza Horizon 5 Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "Xbox Series X|S, PC" },
      { key: "Genre", value: "Racing" },
      { key: "Players", value: "1-12" },
      { key: "Cars", value: "500+" },
    ],
    tags: ["xbox", "forza", "racing", "open-world", "mexico", "exclusive", "horizon"],
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 178,
    views: 4500,
  },
  {
    name: "Starfield",
    categorySlug: "xbox-series-xs-games",
    brand: "Microsoft",
    price: 69.99,
    stockQuantity: 25,
    sku: "RG-XBX-0003",
    description: "Explore the cosmos with a custom character and enjoy an unparalleled freedom as you embark on an epic journey to answer humanity's greatest mystery.",
    shortDescription: "Epic space RPG from the creators of Skyrim",
    mainImage: img(IMAGES.games, "starfield"),
    galleryImages: [
      { url: img(IMAGES.games, "starfield-g1"), alt: "Starfield Cover" },
      { url: img(IMAGES.games, "starfield-g2"), alt: "Starfield Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "Xbox Series X|S, PC" },
      { key: "Genre", value: "RPG" },
      { key: "Players", value: "1" },
      { key: "Storage", value: "125 GB" },
    ],
    tags: ["xbox", "starfield", "rpg", "space", "bethesda", "exclusive", "exploration"],
    isNewArrival: true,
    isTrending: true,
    rating: 4.4,
    reviewCount: 98,
    views: 3800,
  },
  {
    name: "Senua's Saga: Hellblade II",
    categorySlug: "xbox-series-xs-games",
    brand: "Microsoft",
    price: 49.99,
    stockQuantity: 20,
    sku: "RG-XBX-0004",
    description: "Senua returns in a brutal Viking Iceland where reality is a monster and the gods and demons of her mind are ever present.",
    shortDescription: "Brutal Viking journey through psychosis",
    mainImage: img(IMAGES.games, "hellblade"),
    galleryImages: [
      { url: img(IMAGES.games, "hellblade-g1"), alt: "Hellblade II Cover" },
      { url: img(IMAGES.games, "hellblade-g2"), alt: "Hellblade II Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "Xbox Series X|S, PC" },
      { key: "Genre", value: "Action-Adventure" },
      { key: "Players", value: "1" },
    ],
    tags: ["xbox", "hellblade", "action", "adventure", "ninja-theory", "exclusive", "vikings"],
    rating: 4.6,
    reviewCount: 67,
    views: 2200,
  },
  {
    name: "Hi-Fi Rush",
    categorySlug: "xbox-indie-games",
    brand: "Microsoft",
    price: 29.99,
    stockQuantity: 22,
    sku: "RG-XBI-0001",
    description: "Discover the rhythmic world of Hi-Fi Rush! Feel the beat as you slash, combo, and rock out in this action rhythm game.",
    shortDescription: "Action rhythm game where combat moves to the beat",
    mainImage: img(IMAGES.games, "hifi"),
    galleryImages: [
      { url: img(IMAGES.games, "hifi-g1"), alt: "Hi-Fi Rush Cover" },
    ],
    specifications: [
      { key: "Platform", value: "Xbox Series X|S, PC" },
      { key: "Genre", value: "Action Rhythm" },
      { key: "Players", value: "1" },
    ],
    tags: ["xbox", "indie", "rhythm", "action", "tango", "colorful", "music"],
    rating: 4.7,
    reviewCount: 89,
    views: 1800,
  },
  {
    name: "Sea of Thieves",
    categorySlug: "xbox-indie-games",
    brand: "Microsoft",
    price: 39.99,
    stockQuantity: 28,
    sku: "RG-XBI-0002",
    description: "Be the pirate you want to be in this shared-world adventure game. Sail, fight, and explore with friends or solo.",
    shortDescription: "Shared-world pirate adventure",
    mainImage: img(IMAGES.games, "seaofthieves"),
    galleryImages: [
      { url: img(IMAGES.games, "sot-g1"), alt: "Sea of Thieves Cover" },
    ],
    specifications: [
      { key: "Platform", value: "Xbox Series X|S, PC" },
      { key: "Genre", value: "Action-Adventure" },
      { key: "Players", value: "1-4" },
    ],
    tags: ["xbox", "indie", "pirate", "adventure", "multiplayer", "rare", "open-world"],
    isTrending: true,
    rating: 4.5,
    reviewCount: 134,
    views: 2900,
  },
  {
    name: "Microsoft Flight Simulator",
    categorySlug: "xbox-exclusives",
    brand: "Microsoft",
    price: 59.99,
    stockQuantity: 15,
    sku: "RG-XBX-0005",
    description: "Travel the world in amazing detail with over 37,000 airports, 1.5 billion buildings, and real-time weather.",
    shortDescription: "The most realistic flight simulator ever made",
    mainImage: img(IMAGES.games, "msfs"),
    galleryImages: [
      { url: img(IMAGES.games, "msfs-g1"), alt: "MSFS Cover" },
      { url: img(IMAGES.games, "msfs-g2"), alt: "MSFS Gameplay" },
    ],
    specifications: [
      { key: "Platform", value: "Xbox Series X|S, PC" },
      { key: "Genre", value: "Simulation" },
      { key: "Players", value: "1" },
      { key: "Airports", value: "37,000+" },
    ],
    tags: ["xbox", "simulation", "flight", "exclusive", "microsoft", "realistic", "open-world"],
    rating: 4.7,
    reviewCount: 112,
    views: 2600,
  },
  // ── PC Gaming ──
  {
    name: "Samsung Odyssey G7 32\" Curved Gaming Monitor",
    categorySlug: "gaming-monitors",
    brand: "Samsung",
    price: 449.99,
    salePrice: 379.99,
    stockQuantity: 12,
    sku: "RG-PC-0001",
    description: "32-inch curved gaming monitor with QHD resolution, 240Hz refresh rate, 1ms response time, and 1000R curvature for immersive gaming.",
    shortDescription: "32\" QHD 240Hz curved gaming monitor",
    mainImage: IMAGES.monitors,
    galleryImages: [
      { url: img(IMAGES.monitors, "g1"), alt: "Odyssey G7 Front" },
      { url: img(IMAGES.monitors, "g2"), alt: "Odyssey G7 Curved" },
    ],
    specifications: [
      { key: "Size", value: "32 inches" },
      { key: "Resolution", value: "2560 x 1440 (QHD)" },
      { key: "Refresh Rate", value: "240Hz" },
      { key: "Response Time", value: "1ms GTG" },
      { key: "Panel", value: "VA, 1000R Curved" },
    ],
    tags: ["monitor", "samsung", "curved", "qhd", "240hz", "gaming", "hdr"],
    isFeatured: true,
    rating: 4.7,
    reviewCount: 78,
    views: 2400,
  },
  {
    name: "LG UltraGear 27\" 4K Gaming Monitor",
    categorySlug: "gaming-monitors",
    brand: "LG",
    price: 549.99,
    stockQuantity: 8,
    sku: "RG-PC-0002",
    description: "27-inch 4K UHD IPS gaming monitor with 144Hz refresh rate, 1ms response time, and NVIDIA G-SYNC compatibility.",
    shortDescription: "27\" 4K 144Hz IPS gaming monitor",
    mainImage: img(IMAGES.monitors, "lg"),
    galleryImages: [
      { url: img(IMAGES.monitors, "lg-g1"), alt: "LG UltraGear Front" },
      { url: img(IMAGES.monitors, "lg-g2"), alt: "LG UltraGear Side" },
    ],
    specifications: [
      { key: "Size", value: "27 inches" },
      { key: "Resolution", value: "3840 x 2160 (4K UHD)" },
      { key: "Refresh Rate", value: "144Hz" },
      { key: "Response Time", value: "1ms GTG" },
      { key: "Panel", value: "Nano IPS" },
    ],
    tags: ["monitor", "lg", "4k", "144hz", "ips", "gaming", "g-sync"],
    isNewArrival: true,
    rating: 4.8,
    reviewCount: 45,
    views: 1800,
  },
  {
    name: "NVIDIA GeForce RTX 4070 Ti Super",
    categorySlug: "graphics-cards",
    brand: "NVIDIA",
    price: 799.99,
    stockQuantity: 5,
    sku: "RG-PC-0003",
    description: "Supercharged with AI and ray tracing performance. The RTX 4070 Ti Super delivers exceptional 4K gaming with DLSS 3 and frame generation.",
    shortDescription: "AI-powered 4K gaming GPU with DLSS 3",
    mainImage: img(IMAGES.monitors, "gpu"),
    galleryImages: [
      { url: img(IMAGES.monitors, "gpu-g1"), alt: "RTX 4070 Ti Super Front" },
      { url: img(IMAGES.monitors, "gpu-g2"), alt: "RTX 4070 Ti Super Side" },
    ],
    specifications: [
      { key: "CUDA Cores", value: "8448" },
      { key: "Memory", value: "16 GB GDDR6X" },
      { key: "Boost Clock", value: "2.61 GHz" },
      { key: "TDP", value: "285W" },
      { key: "Features", value: "DLSS 3, Ray Tracing, Frame Generation" },
    ],
    tags: ["gpu", "nvidia", "rtx", "4070", "graphics-card", "dlss", "ray-tracing", "4k"],
    isFeatured: true,
    isTrending: true,
    rating: 4.7,
    reviewCount: 34,
    views: 3200,
  },
  {
    name: "AMD Radeon RX 7800 XT",
    categorySlug: "graphics-cards",
    brand: "AMD",
    price: 499.99,
    stockQuantity: 8,
    sku: "RG-PC-0004",
    description: "Exceptional 1440p gaming performance with 16GB VRAM, ray tracing support, and AMD FSR 3 for incredible value.",
    shortDescription: "1440p powerhouse with 16GB VRAM",
    mainImage: img(IMAGES.monitors, "amd-gpu"),
    galleryImages: [
      { url: img(IMAGES.monitors, "amd-gpu-g1"), alt: "RX 7800 XT Front" },
    ],
    specifications: [
      { key: "Stream Processors", value: "3840" },
      { key: "Memory", value: "16 GB GDDR6" },
      { key: "Boost Clock", value: "2.43 GHz" },
      { key: "TDP", value: "263W" },
    ],
    tags: ["gpu", "amd", "radeon", "7800xt", "graphics-card", "1440p", "value"],
    rating: 4.6,
    reviewCount: 56,
    views: 2400,
  },
  {
    name: "ASUS ROG Strix G16 Gaming Laptop",
    categorySlug: "gaming-laptops",
    brand: "ASUS",
    price: 1799.99,
    salePrice: 1599.99,
    stockQuantity: 6,
    sku: "RG-PC-0005",
    description: "16-inch gaming laptop with Intel Core i9, NVIDIA RTX 4070, 16GB DDR5, 1TB PCIe SSD, and 240Hz display.",
    shortDescription: "16\" gaming laptop with i9 and RTX 4070",
    mainImage: img(IMAGES.monitors, "laptop"),
    galleryImages: [
      { url: img(IMAGES.monitors, "laptop-g1"), alt: "ROG Strix G16 Front" },
      { url: img(IMAGES.monitors, "laptop-g2"), alt: "ROG Strix G16 Keyboard" },
    ],
    specifications: [
      { key: "CPU", value: "Intel Core i9-14900HX" },
      { key: "GPU", value: "NVIDIA RTX 4070 8GB" },
      { key: "RAM", value: "16 GB DDR5" },
      { key: "Storage", value: "1 TB PCIe SSD" },
      { key: "Display", value: "16\" QHD 240Hz" },
    ],
    tags: ["laptop", "asus", "rog", "gaming", "i9", "rtx-4070", "portable"],
    isFeatured: true,
    rating: 4.6,
    reviewCount: 23,
    views: 1500,
  },
  {
    name: "Elgato Stream Deck MK.2",
    categorySlug: "streaming-equipment",
    brand: "Elgato",
    price: 149.99,
    stockQuantity: 20,
    sku: "RG-PC-0006",
    description: "15 customizable LCD keys for controlling audio, video, and lighting. Perfect for streamers and content creators.",
    shortDescription: "15-key controller for streamers and creators",
    mainImage: img(IMAGES.monitors, "streamdeck"),
    galleryImages: [
      { url: img(IMAGES.monitors, "streamdeck-g1"), alt: "Stream Deck Front" },
      { url: img(IMAGES.monitors, "streamdeck-g2"), alt: "Stream Deck Keys" },
    ],
    specifications: [
      { key: "Keys", value: "15 customizable LCD keys" },
      { key: "Connectivity", value: "USB-C" },
      { key: "Software", value: "Elgato Stream Deck" },
      { key: "Stand", value: "Adjustable stand included" },
    ],
    tags: ["streaming", "elgato", "stream-deck", "content-creation", "broadcasting", "controller"],
    isTrending: true,
    rating: 4.8,
    reviewCount: 89,
    views: 2100,
  },
  {
    name: "Blue Yeti X USB Microphone",
    categorySlug: "streaming-equipment",
    brand: "Blue",
    price: 149.99,
    salePrice: 119.99,
    stockQuantity: 15,
    sku: "RG-PC-0007",
    description: "Professional USB condenser microphone with 4-capsule array for clear, powerful broadcast-quality sound.",
    shortDescription: "Professional USB mic with 4-capsule array",
    mainImage: img(IMAGES.monitors, "mic"),
    galleryImages: [
      { url: img(IMAGES.monitors, "mic-g1"), alt: "Yeti X Front" },
      { url: img(IMAGES.monitors, "mic-g2"), alt: "Yeti X Side" },
    ],
    specifications: [
      { key: "Capsules", value: "4-capsule array" },
      { key: "Patterns", value: "Cardioid, Bidirectional, Omnidirectional, Stereo" },
      { key: "Bit Depth", value: "24-bit" },
      { key: "Sample Rate", value: "48 kHz" },
    ],
    tags: ["microphone", "blue", "usb", "streaming", "podcast", "broadcasting", "content-creation"],
    rating: 4.5,
    reviewCount: 67,
    views: 1800,
  },
  {
    name: "Logitech G502 X PLUS Wireless Gaming Mouse",
    categorySlug: "pc-peripherals",
    brand: "Logitech",
    price: 159.99,
    stockQuantity: 18,
    sku: "RG-PC-0008",
    description: "The iconic G502, reimagined. LIGHTFORCE hybrid optical-mechanical switches, HERO 25K sensor, and LIGHTSPEED wireless.",
    shortDescription: "Reimagined G502 with hybrid switches",
    mainImage: img(IMAGES.mouse, "g502"),
    galleryImages: [
      { url: img(IMAGES.mouse, "g502-g1"), alt: "G502 X PLUS Top" },
      { url: img(IMAGES.mouse, "g502-g2"), alt: "G502 X PLUS Side" },
    ],
    specifications: [
      { key: "Sensor", value: "HERO 25K" },
      { key: "DPI", value: "Up to 25,600" },
      { key: "Weight", value: "106g" },
      { key: "Battery", value: "Up to 95 hours" },
      { key: "Switches", value: "LIGHTFORCE hybrid" },
    ],
    tags: ["mouse", "logitech", "wireless", "g502", "gaming", "hybrid", "rgb"],
    rating: 4.7,
    reviewCount: 78,
    views: 2200,
  },
  // ── Gaming Merchandise ──
  {
    name: "Retro Gaming Pixel Art T-Shirt",
    categorySlug: "gaming-merch",
    brand: "RetroGaming",
    price: 29.99,
    stockQuantity: 50,
    sku: "RG-MER-0001",
    description: "Premium cotton t-shirt featuring classic pixel art gaming design. Available in multiple sizes for the ultimate retro gamer.",
    shortDescription: "Premium pixel art t-shirt for retro gamers",
    mainImage: img(IMAGES.games, "tshirt"),
    galleryImages: [
      { url: img(IMAGES.games, "tshirt-g1"), alt: "T-Shirt Front" },
      { url: img(IMAGES.games, "tshirt-g2"), alt: "T-Shirt Back" },
    ],
    specifications: [
      { key: "Material", value: "100% Premium Cotton" },
      { key: "Sizes", value: "S, M, L, XL, XXL" },
      { key: "Care", value: "Machine washable" },
      { key: "Design", value: "Pixel art gaming print" },
    ],
    tags: ["merchandise", "t-shirt", "retro", "pixel-art", "gaming", "apparel", "cotton"],
    rating: 4.4,
    reviewCount: 56,
    views: 1200,
  },
  {
    name: "Gaming Headset Stand with USB Hub",
    categorySlug: "gaming-merch",
    brand: "RetroGaming",
    price: 39.99,
    stockQuantity: 35,
    sku: "RG-MER-0002",
    description: "Premium aluminum headset stand with built-in 4-port USB 3.0 hub and RGB lighting. The perfect addition to any gaming desk.",
    shortDescription: "Aluminum headset stand with USB hub and RGB",
    mainImage: img(IMAGES.headsets, "stand"),
    galleryImages: [
      { url: img(IMAGES.headsets, "stand-g1"), alt: "Stand Front" },
      { url: img(IMAGES.headsets, "stand-g2"), alt: "Stand RGB" },
    ],
    specifications: [
      { key: "Material", value: "Aluminum alloy" },
      { key: "USB Ports", value: "4x USB 3.0" },
      { key: "Lighting", value: "RGB LED base" },
      { key: "Max Load", value: "5 kg" },
    ],
    tags: ["merchandise", "headset-stand", "usb-hub", "rgb", "gaming", "desk", "aluminum"],
    rating: 4.5,
    reviewCount: 34,
    views: 900,
  },
  {
    name: "Retro Gaming Coaster Set (6 Pack)",
    categorySlug: "gaming-merch",
    brand: "RetroGaming",
    price: 24.99,
    stockQuantity: 40,
    sku: "RG-MER-0003",
    description: "Set of 6 retro gaming themed coasters featuring iconic pixel art designs. Cork-backed for surface protection.",
    shortDescription: "6-pack retro gaming pixel art coasters",
    mainImage: img(IMAGES.games, "coasters"),
    galleryImages: [
      { url: img(IMAGES.games, "coasters-g1"), alt: "Coasters Set" },
    ],
    specifications: [
      { key: "Quantity", value: "6 coasters" },
      { key: "Material", value: "Ceramic with cork backing" },
      { key: "Size", value: "4 inches diameter" },
      { key: "Design", value: "Retro pixel art" },
    ],
    tags: ["merchandise", "coasters", "retro", "pixel-art", "gaming", "home", "accessories"],
    rating: 4.3,
    reviewCount: 28,
    views: 600,
  },
  {
    name: "Gaming Mouse Bungee with RGB",
    categorySlug: "gaming-merch",
    brand: "RetroGaming",
    price: 29.99,
    stockQuantity: 25,
    sku: "RG-MER-0004",
    description: "Flexible mouse bungee with weighted base and RGB lighting. Eliminates cable drag for smoother gaming movements.",
    shortDescription: "RGB mouse bungee for cable-free feel",
    mainImage: img(IMAGES.mouse, "bungee"),
    galleryImages: [
      { url: img(IMAGES.mouse, "bungee-g1"), alt: "Bungee Front" },
      { url: img(IMAGES.mouse, "bungee-g2"), alt: "Bungee RGB" },
    ],
    specifications: [
      { key: "Material", value: "ABS + Rubber arm" },
      { key: "Base", value: "Weighted non-slip" },
      { key: "Lighting", value: "RGB LED" },
      { key: "Compatibility", value: "All wired mice" },
    ],
    tags: ["merchandise", "mouse-bungee", "rgb", "gaming", "cable-management", "accessories"],
    rating: 4.2,
    reviewCount: 22,
    views: 500,
  },
  {
    name: "PS5 DualSense Controller Skin - Camo Green",
    categorySlug: "gaming-merch",
    brand: "RetroGaming",
    price: 14.99,
    stockQuantity: 45,
    sku: "RG-MER-0005",
    description: "Premium vinyl skin for PS5 DualSense controller in camo green pattern. Easy to apply and remove without residue.",
    shortDescription: "Premium vinyl skin for DualSense controller",
    mainImage: img(IMAGES.controllers, "skin"),
    galleryImages: [
      { url: img(IMAGES.controllers, "skin-g1"), alt: "Skin Front" },
    ],
    specifications: [
      { key: "Material", value: "Premium vinyl" },
      { key: "Compatibility", value: "PS5 DualSense" },
      { key: "Pattern", value: "Camo Green" },
      { key: "Application", value: "Easy apply/remove" },
    ],
    tags: ["merchandise", "skin", "dualsense", "ps5", "camo", "vinyl", "customization"],
    rating: 4.1,
    reviewCount: 18,
    views: 400,
  },
  {
    name: "Retro Gaming Enamel Pin Set",
    categorySlug: "gaming-merch",
    brand: "RetroGaming",
    price: 19.99,
    stockQuantity: 30,
    sku: "RG-MER-0006",
    description: "Set of 4 high-quality enamel pins featuring retro gaming icons: controller, cartridge, joystick, and pixel heart.",
    shortDescription: "4-piece retro gaming enamel pin collection",
    mainImage: img(IMAGES.games, "pins"),
    galleryImages: [
      { url: img(IMAGES.games, "pins-g1"), alt: "Pin Set" },
    ],
    specifications: [
      { key: "Quantity", value: "4 pins" },
      { key: "Material", value: "Hard enamel with metal base" },
      { key: "Size", value: "1-1.5 inches" },
      { key: "Back", value: "Butterfly clutch" },
    ],
    tags: ["merchandise", "pins", "enamel", "retro", "collectible", "gaming", "accessories"],
    rating: 4.6,
    reviewCount: 42,
    views: 800,
  },
  {
    name: "Gaming Desk Mat XXL - Retro Grid",
    categorySlug: "gaming-merch",
    brand: "RetroGaming",
    price: 34.99,
    stockQuantity: 20,
    sku: "RG-MER-0007",
    description: "Oversized desk mat with retro grid design, stitched edges, and anti-slip rubber base. Perfect for keyboard and mouse.",
    shortDescription: "XXL desk mat with retro grid aesthetic",
    mainImage: img(IMAGES.mouse, "deskmat"),
    galleryImages: [
      { url: img(IMAGES.mouse, "deskmat-g1"), alt: "Desk Mat Top" },
      { url: img(IMAGES.mouse, "deskmat-g2"), alt: "Desk Mat Side" },
    ],
    specifications: [
      { key: "Size", value: "900mm x 400mm x 4mm" },
      { key: "Material", value: "Cloth surface, rubber base" },
      { key: "Edges", value: "Stitched" },
      { key: "Design", value: "Retro grid pattern" },
    ],
    tags: ["merchandise", "desk-mat", "xxl", "retro", "gaming", "mousepad", "grid"],
    rating: 4.4,
    reviewCount: 31,
    views: 700,
  },
  {
    name: "Retro Gaming Logo Hoodie",
    categorySlug: "gaming-merch",
    brand: "RetroGaming",
    price: 54.99,
    stockQuantity: 25,
    sku: "RG-MER-0008",
    description: "Comfortable pullover hoodie with embroidered RetroGaming logo. Heavyweight cotton-blend for ultimate comfort.",
    shortDescription: "Embroidered logo hoodie for gaming sessions",
    mainImage: img(IMAGES.games, "hoodie"),
    galleryImages: [
      { url: img(IMAGES.games, "hoodie-g1"), alt: "Hoodie Front" },
      { url: img(IMAGES.games, "hoodie-g2"), alt: "Hoodie Detail" },
    ],
    specifications: [
      { key: "Material", value: "80% Cotton, 20% Polyester" },
      { key: "Sizes", value: "S, M, L, XL, XXL" },
      { key: "Design", value: "Embroidered logo" },
      { key: "Weight", value: "320 GSM" },
    ],
    tags: ["merchandise", "hoodie", "retro", "gaming", "apparel", "embroidered", "comfort"],
    isTrending: true,
    rating: 4.5,
    reviewCount: 38,
    views: 1100,
  },
];

const CATEGORIES = [
  // Parent categories
  { name: "Gaming Consoles", slug: "gaming-consoles", description: "All gaming consoles from PlayStation, Xbox, Nintendo, and more", sortOrder: 0, image: IMAGES.consoles, platform: "general" },
  { name: "Gaming Accessories", slug: "gaming-accessories", description: "Controllers, headsets, chairs, and more gaming gear", sortOrder: 1, image: IMAGES.controllers, platform: "general" },
  { name: "PS Games", slug: "ps-games", description: "PlayStation games across all generations", sortOrder: 2, image: IMAGES.games, platform: "playstation" },
  { name: "Xbox Games", slug: "xbox-games", description: "Xbox games for Series X|S, One, and more", sortOrder: 3, image: IMAGES.games, platform: "xbox" },
  { name: "PC Gaming", slug: "pc-gaming", description: "Monitors, graphics cards, laptops, and PC peripherals", sortOrder: 4, image: IMAGES.monitors, platform: "pc" },
  { name: "Gaming Merchandise", slug: "gaming-merchandise", description: "Apparel, collectibles, and gaming lifestyle products", sortOrder: 5, image: IMAGES.games, platform: "general" },
];

const SUBCATEGORIES: { name: string; slug: string; parentSlug: string; description: string; image: string; platform: string }[] = [
  // Gaming Consoles
  { name: "PlayStation 5", slug: "playstation-5", parentSlug: "gaming-consoles", description: "Sony PlayStation 5 console", image: IMAGES.consoles, platform: "playstation" },
  { name: "PlayStation 5 Slim", slug: "playstation-5-slim", parentSlug: "gaming-consoles", description: "Sony PlayStation 5 Slim console", image: img(IMAGES.consoles, "slim"), platform: "playstation" },
  { name: "PlayStation 5 Pro", slug: "playstation-5-pro", parentSlug: "gaming-consoles", description: "Sony PlayStation 5 Pro console", image: img(IMAGES.consoles, "pro"), platform: "playstation" },
  { name: "PlayStation 4", slug: "playstation-4", parentSlug: "gaming-consoles", description: "Sony PlayStation 4 consoles", image: img(IMAGES.consoles, "ps4"), platform: "playstation" },
  { name: "Xbox Series X", slug: "xbox-series-x", parentSlug: "gaming-consoles", description: "Microsoft Xbox Series X console", image: img(IMAGES.consoles, "xsx"), platform: "xbox" },
  { name: "Xbox Series S", slug: "xbox-series-s", parentSlug: "gaming-consoles", description: "Microsoft Xbox Series S console", image: img(IMAGES.consoles, "xss"), platform: "xbox" },
  { name: "Xbox One", slug: "xbox-one", parentSlug: "gaming-consoles", description: "Microsoft Xbox One consoles", image: img(IMAGES.consoles, "xboxone"), platform: "xbox" },
  { name: "Nintendo Switch", slug: "nintendo-switch", parentSlug: "gaming-consoles", description: "Nintendo Switch console", image: IMAGES.switch, platform: "nintendo" },
  { name: "Nintendo Switch OLED", slug: "nintendo-switch-oled", parentSlug: "gaming-consoles", description: "Nintendo Switch OLED Model", image: img(IMAGES.switch, "oled"), platform: "nintendo" },
  { name: "Steam Deck", slug: "steam-deck", parentSlug: "gaming-consoles", description: "Valve Steam Deck handheld", image: img(IMAGES.consoles, "steamdeck"), platform: "pc" },
  // Gaming Accessories
  { name: "Controllers", slug: "controllers", parentSlug: "gaming-accessories", description: "Gaming controllers for all platforms", image: IMAGES.controllers, platform: "general" },
  { name: "Headsets", slug: "headsets", parentSlug: "gaming-accessories", description: "Gaming headsets and headphones", image: IMAGES.headsets, platform: "general" },
  { name: "Charging Stations", slug: "charging-stations", parentSlug: "gaming-accessories", description: "Controller and console charging solutions", image: img(IMAGES.controllers, "charge"), platform: "general" },
  { name: "Gaming Mouse", slug: "gaming-mouse", parentSlug: "gaming-accessories", description: "High-performance gaming mice", image: IMAGES.mouse, platform: "general" },
  { name: "Gaming Keyboards", slug: "gaming-keyboards", parentSlug: "gaming-accessories", description: "Mechanical and gaming keyboards", image: IMAGES.keyboards, platform: "general" },
  { name: "Gaming Mouse Pads", slug: "gaming-mouse-pads", parentSlug: "gaming-accessories", description: "Extended and standard gaming mouse pads", image: img(IMAGES.mouse, "pad"), platform: "general" },
  { name: "Gaming Chairs", slug: "gaming-chairs", parentSlug: "gaming-accessories", description: "Ergonomic gaming chairs", image: IMAGES.chairs, platform: "general" },
  { name: "Capture Cards", slug: "capture-cards", parentSlug: "gaming-accessories", description: "Video capture cards for streaming", image: img(IMAGES.consoles, "capture"), platform: "general" },
  { name: "Cable Management", slug: "cable-management", parentSlug: "gaming-accessories", description: "Cable organizers and management", image: img(IMAGES.consoles, "cables"), platform: "general" },
  { name: "Skin & Covers", slug: "skin-covers", parentSlug: "gaming-accessories", description: "Console and controller skins", image: img(IMAGES.consoles, "cover"), platform: "general" },
  // PS Games
  { name: "PS5 Games", slug: "ps5-games", parentSlug: "ps-games", description: "PlayStation 5 games", image: IMAGES.games, platform: "playstation" },
  { name: "PS4 Games", slug: "ps4-games", parentSlug: "ps-games", description: "PlayStation 4 games", image: img(IMAGES.games, "ps4"), platform: "playstation" },
  { name: "PS3 Games", slug: "ps3-games", parentSlug: "ps-games", description: "PlayStation 3 games", image: img(IMAGES.games, "ps3"), platform: "playstation" },
  { name: "PS2 Games", slug: "ps2-games", parentSlug: "ps-games", description: "PlayStation 2 games", image: img(IMAGES.games, "ps2"), platform: "playstation" },
  { name: "PS Vita Games", slug: "ps-vita-games", parentSlug: "ps-games", description: "PlayStation Vita games", image: img(IMAGES.games, "vita"), platform: "playstation" },
  { name: "PlayStation Indies", slug: "playstation-indies", parentSlug: "ps-games", description: "Independent games on PlayStation", image: img(IMAGES.games, "indie"), platform: "playstation" },
  { name: "PlayStation Exclusives", slug: "playstation-exclusives", parentSlug: "ps-games", description: "PlayStation exclusive titles", image: img(IMAGES.games, "exclusive"), platform: "playstation" },
  // Xbox Games
  { name: "Xbox Series X|S Games", slug: "xbox-series-xs-games", parentSlug: "xbox-games", description: "Games for Xbox Series X and Series S", image: img(IMAGES.games, "xbox"), platform: "xbox" },
  { name: "Xbox One Games", slug: "xbox-one-games", parentSlug: "xbox-games", description: "Games for Xbox One", image: img(IMAGES.games, "xboxone"), platform: "xbox" },
  { name: "Xbox Game Pass", slug: "xbox-game-pass", parentSlug: "xbox-games", description: "Xbox Game Pass subscriptions", image: img(IMAGES.games, "gamepass"), platform: "xbox" },
  { name: "Xbox Indie Games", slug: "xbox-indie-games", parentSlug: "xbox-games", description: "Independent games on Xbox", image: img(IMAGES.games, "xboxindie"), platform: "xbox" },
  { name: "Xbox Exclusives", slug: "xbox-exclusives", parentSlug: "xbox-games", description: "Xbox exclusive titles", image: img(IMAGES.games, "xboxexcl"), platform: "xbox" },
  // PC Gaming
  { name: "Gaming Monitors", slug: "gaming-monitors", parentSlug: "pc-gaming", description: "High-refresh gaming monitors", image: IMAGES.monitors, platform: "pc" },
  { name: "Graphics Cards", slug: "graphics-cards", parentSlug: "pc-gaming", description: "NVIDIA and AMD graphics cards", image: img(IMAGES.monitors, "gpu"), platform: "pc" },
  { name: "Gaming Laptops", slug: "gaming-laptops", parentSlug: "pc-gaming", description: "Portable gaming laptops", image: img(IMAGES.monitors, "laptop"), platform: "pc" },
  { name: "PC Peripherals", slug: "pc-peripherals", parentSlug: "pc-gaming", description: "PC gaming peripherals", image: IMAGES.mouse, platform: "pc" },
  { name: "Streaming Equipment", slug: "streaming-equipment", parentSlug: "pc-gaming", description: "Microphones, cameras, and streaming gear", image: img(IMAGES.monitors, "streamdeck"), platform: "pc" },
  // Gaming Merchandise
  { name: "Gaming Merchandise", slug: "gaming-merch", parentSlug: "gaming-merchandise", description: "Apparel, collectibles, and gaming lifestyle", image: img(IMAGES.games, "merch"), platform: "general" },
];

const BANNERS = [
  {
    title: "Level Up Your Gaming",
    subtitle: "New arrivals every week",
    description: "Discover the latest consoles, games, and accessories at RetroGaming. Your one-stop shop for all things gaming.",
    image: IMAGES.consoles,
    ctaText: "Shop Now",
    ctaLink: "/products",
    secondaryCtaText: "View Deals",
    secondaryCtaLink: "/deals",
    position: "hero" as const,
    sortOrder: 0,
    overlayColor: "#000000",
    overlayOpacity: 0.5,
    badge: "NEW ARRIVALS",
  },
  {
    title: "PlayStation 5 Collection",
    subtitle: "Experience next-gen gaming",
    description: "Explore our complete PS5 lineup including the new Slim and Pro models. Games, accessories, and more.",
    image: img(IMAGES.consoles, "ps5-promo"),
    ctaText: "Shop PS5",
    ctaLink: "/category/playstation-5",
    secondaryCtaText: "PS5 Games",
    secondaryCtaLink: "/category/ps5-games",
    position: "promotional" as const,
    sortOrder: 1,
    overlayColor: "#003087",
    overlayOpacity: 0.6,
    badge: "PS5",
  },
  {
    title: "Xbox Game Pass Deals",
    subtitle: "Hundreds of games at your fingertips",
    description: "Get unlimited access to hundreds of games with Xbox Game Pass. Plus save on Xbox consoles and accessories.",
    image: img(IMAGES.consoles, "xbox-promo"),
    ctaText: "Shop Xbox",
    ctaLink: "/category/xbox-series-x",
    secondaryCtaText: "Xbox Games",
    secondaryCtaLink: "/category/xbox-series-xs-games",
    position: "promotional" as const,
    sortOrder: 2,
    overlayColor: "#107C10",
    overlayOpacity: 0.6,
    badge: "XBOX",
  },
  {
    title: "Accessories Sale",
    subtitle: "Upgrade your setup",
    description: "Save up to 30% on premium gaming accessories including controllers, headsets, chairs, and more.",
    image: IMAGES.controllers,
    ctaText: "Shop Accessories",
    ctaLink: "/category/gaming-accessories",
    secondaryCtaText: "View All Deals",
    secondaryCtaLink: "/deals",
    position: "promotional" as const,
    sortOrder: 3,
    overlayColor: "#FF6B00",
    overlayOpacity: 0.6,
    badge: "SALE",
  },
  {
    title: "Game Deals of the Week",
    subtitle: "Top titles at unbeatable prices",
    description: "Check out this week's hottest game deals across PS5, Xbox, and PC. Limited time offers.",
    image: img(IMAGES.games, "deals"),
    ctaText: "Shop Games",
    ctaLink: "/category/ps5-games",
    secondaryCtaText: "All Deals",
    secondaryCtaLink: "/deals",
    position: "category" as const,
    sortOrder: 4,
    overlayColor: "#E4002B",
    overlayOpacity: 0.5,
    badge: "DEALS",
  },
  {
    title: "Back to Gaming",
    subtitle: "Everything you need to play",
    description: "Whether you're upgrading or starting fresh, we've got consoles, games, and accessories for every gamer.",
    image: img(IMAGES.consoles, "back-to-gaming"),
    ctaText: "Explore",
    ctaLink: "/products",
    secondaryCtaText: "Best Sellers",
    secondaryCtaLink: "/products?sort=bestSeller",
    position: "hero" as const,
    sortOrder: 5,
    overlayColor: "#6B21A8",
    overlayOpacity: 0.5,
    badge: "HOT",
  },
];

const COUPONS = [
  {
    code: "WELCOME10",
    type: "percentage" as const,
    value: 10,
    minOrderAmount: 50,
    maxDiscountAmount: 100,
    usageLimit: 1000,
    usedCount: 0,
    isActive: true,
    expiresAt: new Date("2027-12-31"),
  },
  {
    code: "GAMER20",
    type: "percentage" as const,
    value: 20,
    minOrderAmount: 100,
    maxDiscountAmount: 200,
    usageLimit: 500,
    usedCount: 0,
    isActive: true,
    expiresAt: new Date("2027-06-30"),
  },
  {
    code: "FREESHIP",
    type: "fixed" as const,
    value: 9.99,
    minOrderAmount: 25,
    usageLimit: 2000,
    usedCount: 0,
    isActive: true,
    expiresAt: new Date("2027-12-31"),
  },
  {
    code: "PS5DEAL",
    type: "fixed" as const,
    value: 50,
    minOrderAmount: 399,
    usageLimit: 200,
    usedCount: 0,
    isActive: true,
    expiresAt: new Date("2027-03-31"),
  },
];

async function seed() {
  console.log("Connecting to MongoDB...");
  await connectDB();
  console.log("Connected to MongoDB\n");

  // ── Clear existing data ──
  console.log("Clearing existing data...");
  await Promise.all([
    Category.deleteMany({}),
    Product.deleteMany({}),
    Banner.deleteMany({}),
    Coupon.deleteMany({}),
  ]);
  console.log("All existing data cleared\n");

  // ── Seed Categories ──
  console.log("Seeding categories...");
  const createdParents = await Category.insertMany(
    CATEGORIES.map((cat) => ({
      name: cat.name,
      slug: cat.slug,
      description: cat.description,
      image: cat.image,
      platform: cat.platform,
      isActive: true,
      sortOrder: cat.sortOrder,
    }))
  );
  console.log(`  Created ${createdParents.length} parent categories`);

  const parentBySlug = new Map(createdParents.map((c) => [c.slug, c]));

  const createdSubs = await Category.insertMany(
    SUBCATEGORIES.map((sub, idx) => ({
      name: sub.name,
      slug: sub.slug,
      description: sub.description,
      image: sub.image,
      parentCategory: parentBySlug.get(sub.parentSlug)?._id,
      platform: sub.platform,
      isActive: true,
      sortOrder: idx,
    }))
  );
  console.log(`  Created ${createdSubs.length} subcategories`);
  console.log(`  Total categories: ${createdParents.length + createdSubs.length}\n`);

  const categoryBySlug = new Map(
    [...createdParents, ...createdSubs].map((c) => [c.slug, c])
  );

  // ── Seed Products ──
  console.log("Seeding products...");
  let productCount = 0;
  const productsToInsert = PRODUCTS.map((p) => {
    productCount++;
    const category = categoryBySlug.get(p.categorySlug) || createdParents[0];
    return {
      name: p.name,
      slug: slugify(p.name),
      category: category._id,
      brand: p.brand,
      price: p.price,
      salePrice: p.salePrice,
      discountPercentage: p.salePrice
        ? Math.round(((p.price - p.salePrice) / p.price) * 100)
        : 0,
      stockQuantity: p.stockQuantity,
      sku: p.sku,
      description: p.description,
      shortDescription: p.shortDescription,
      mainImage: p.mainImage,
      galleryImages: p.galleryImages.map((img) => ({
        url: img.url,
        alt: img.alt,
      })),
      specifications: p.specifications,
      tags: p.tags,
      imageTransition: "fade" as const,
      isFeatured: p.isFeatured || false,
      isTrending: p.isTrending || false,
      isNewArrival: p.isNewArrival || false,
      isBestSeller: p.isBestSeller || false,
      isActive: true,
      isOutOfStock: p.stockQuantity <= 0,
      rating: p.rating,
      reviewCount: p.reviewCount,
      views: p.views,
      variants: p.variants || [],
    };
  });

  await Product.insertMany(productsToInsert);
  console.log(`  Created ${productCount} products\n`);

  // ── Seed Banners ──
  console.log("Seeding banners...");
  await Banner.insertMany(
    BANNERS.map((b) => ({
      ...b,
      isActive: true,
    }))
  );
  console.log(`  Created ${BANNERS.length} banners\n`);

  // ── Seed Coupons ──
  console.log("Seeding coupons...");
  await Coupon.insertMany(COUPONS);
  console.log(`  Created ${COUPONS.length} coupons\n`);

  // ── Seed Settings ──
  console.log("Seeding settings...");
  await Settings.findOneAndUpdate({}, DEFAULT_SETTINGS, { upsert: true });
  console.log("  Settings initialized\n");

  // ── Summary ──
  console.log("=== Seed Complete ===");
  console.log(`  Categories: ${createdParents.length + createdSubs.length}`);
  console.log(`  Products: ${productCount}`);
  console.log(`  Banners: ${BANNERS.length}`);
  console.log(`  Coupons: ${COUPONS.length}`);
  console.log(`  Settings: initialized`);
  console.log("====================\n");

  process.exit(0);
}

seed().catch((error) => {
  console.error("Seed failed:", error);
  process.exit(1);
});
